Feature/implement tiovx pad
TexasInstruments/edgeai-gst-plugins pull request #10
Opened 2021-07-19 23:22 UTC by emmadrigal

2021-07-21 18:14 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +    gboolean (*notify_function) (GstElement * notify_element);
Identation

2021-07-21 19:51 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +    gboolean (*notify_function) (GstElement * notify_element);
This is done by the automatic tool, moving it to match the other members causes it to go back to this indentation

2021-07-21 23:18 UTC, dchvs commented on tests/check/libs/gsttiovxpad.c
> +
Extra space.

2021-07-21 23:20 UTC, dchvs commented on tests/check/libs/gsttiovxpad.c
> +  if (sink_pad) {
You can compact this to one line:

`direction = sink_pad ? GST_PAD_SINK : GST_PAD_SRC`

2021-07-21 23:43 UTC, dchvs approved these changes

2021-07-21 23:43 UTC, dchvs commented on tests/check/libs/gsttiovxpad.c
> +  for (npool = 0; npool < gst_query_get_n_allocation_pools (query); ++npool) {
You're the expert with the Gst pools, but I got the question, why do we start at `n=1`, with the statement `++npool`?

2021-07-21 23:43 UTC, dchvs commented on tests/check/libs/gsttiovxpad.c
> +  vx_context context;
These are pointers, initialize them all.

2021-07-22 01:09 UTC, michaelgruner requested changes

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmeta.c
> +  tiovx_meta->image_info.data = (guint8 *) mem_start;
Why do we need access to the data? This feels dangerous.

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  GstTIOVXPad *self = GST_TIOVX_PAD (pad);
pointer guards for all methods please.

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_val_if_fail (pool, NULL);
pointer guards

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  }
This is very random here. Not the place for this.

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  }
Don't do this manually. Just use gst_buffer_copy or gst_buffer_copy_into (can't recall the difference)

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  }
normally this is done right after creating and configuring the pool. No need to place it everywhere.

2021-07-22 01:09 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  G_OBJECT_CLASS (gst_tiovx_pad_parent_class)->finalize (object);
Do you need to free the pool?

2021-07-22 13:24 UTC, emmadrigal commented on tests/check/libs/gsttiovxpad.c
> +  for (npool = 0; npool < gst_query_get_n_allocation_pools (query); ++npool) {
We don't start at 1, the `++npool` is called at the end of the for loop

The difference between `++npool` and `npool++` is relevant for cases like this:
```
 npool = 0;
 i = npool++
```
and 
```
 npool = 0;
 i = ++npool
```

In the first case `i = 0` and in the second one `i = 1`.

2021-07-22 14:15 UTC, emmadrigal commented on tests/check/libs/gsttiovxpad.c
> +  if (sink_pad) {
I've always found that gramatic not very clear. I prefer to be more explicit

2021-07-22 22:08 UTC, merged