Feature/add background image to mosaic
TexasInstruments/edgeai-gst-plugins pull request #102
Opened 2021-09-21 15:59 UTC by emmadrigal

2021-09-21 15:59 UTC, emmadrigal commented
Add support for #86

2021-09-21 17:14 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxmiso.h
> + * @graph_param_id and @node_param_id can be both set to -1 in order ot not use these for node
set to -1 in order or not use?

2021-09-22 04:19 UTC, michaelgruner requested changes

2021-09-22 04:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +    if ((best_width <= background_width) && (best_height <= background_height)) {
This should be an || I believe

2021-09-22 04:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +    }
Simplify this by simply calling `gst_structure_get_int`

2021-09-22 04:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  }
Factor out this, the only difference is that at the end you validate that the size matches the background image. Also, what if the fixate resulted in a smaller size? is this a valid situation?

2021-09-22 20:50 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  }
No, `background_image[0]` is always created by the mosaic_module

2021-09-22 20:51 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    if ((best_width <= background_width) && (best_height <= background_height)) {
No, both best_width and height need to be smaller than the background size

2021-09-22 21:10 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  }
The check for `gst_tiovx_mosaic_validate_candidate_dimension`

Ensures that the candidate_output_structure (which comes from the source caps) is at least big enough, otherwise it exists before trying to fixate

2021-09-23 20:35 UTC, jafet-chaves approved these changes

2021-09-23 22:03 UTC, michaelgruner approved these changes

2021-09-23 22:47 UTC, merged