Enhancement/make all pointer guards consistent
TexasInstruments/edgeai-gst-plugins pull request #104
Opened 2021-09-22 22:20 UTC by jafet-chaves

2021-09-22 23:33 UTC, emmadrigal requested changes

2021-09-22 23:33 UTC, emmadrigal commented on ext/tiovx/gsttiovxmultiscalerpad.h
>      GST_TIOVX, MULTISCALER_PAD, GstTIOVXPad)
I believe this should be:
```
G_DECLARE_FINAL_TYPE (GstTIOVXMultiScalerPad, gst_tiovx_multiscaler_pad,
    GST, TIOVX_MULTISCALER_PAD, GstTIOVXPad)
```

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxallocator.c
> +  g_return_if_fail (klass);
Although generally correct as a point guard, we never call this function, this is rather called by GStreamer directly.

In the cases where we are handling calls from GStreamer we don't use pointer guards

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxallocator.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  g_return_val_if_fail (pool, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  g_return_val_if_fail (pool, GST_FLOW_ERROR);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (obj);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (tiovx_miso_pad);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_if_fail (obj);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  self = GST_TIOVX_MISO (agg);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->deinit_module) {
Why `NULL`? reinit returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->init_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->create_graph) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->get_node_info) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->release_buffer) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->configure_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == klass->deinit_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (NULL == fixated_caps) {
This return a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->init_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->create_graph) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->get_node_info) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->configure_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->deinit_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (self, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->deinit_module) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_if_fail (gobject);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (element, result);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (element, NULL);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_if_fail (element);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (pad, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (pad, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (NULL == klass->compare_caps) {
This returns a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (pad, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (pad, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_if_fail (self);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (trans, ret);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_if_fail (obj);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (trans, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (trans, GST_FLOW_ERROR);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (trans, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (trans, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (NULL == klass->deinit_module) {
All of these functions return a boolean

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxtensorbufferpool.c
> +  g_return_if_fail (klass);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxtensorbufferpool.c
> +  g_return_val_if_fail (pool, FALSE);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxtensorbufferpool.c
> +  g_return_if_fail (pool);
No pointer guard needed for function called by GStreamer

2021-09-22 23:33 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxtensorbufferpool.c
> +  g_return_if_fail (object);
No pointer guard needed for function called by GStreamer

2021-09-23 19:07 UTC, emmadrigal requested changes

2021-09-23 19:07 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  g_return_val_if_fail (agg, FALSE);
You still need to remove these

2021-09-23 21:41 UTC, emmadrigal requested changes

2021-09-23 21:41 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  self = GST_TIOVX_BUFFER_POOL (pool);
Isn't this replicated from the initial declaration?

2021-09-28 14:26 UTC, emmadrigal approved these changes

2021-09-28 22:05 UTC, rrcarlosrodriguez approved these changes

2021-09-28 22:38 UTC, merged