Feature/tiovx context singleton
TexasInstruments/edgeai-gst-plugins pull request #11
Opened 2021-07-21 05:19 UTC by michaelgruner

2021-07-21 15:31 UTC, emmadrigal requested changes

2021-07-21 15:31 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +     which is a valid case of ourse. A normal mutex needs to be used.
Typo `ours`

2021-07-21 15:31 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +  g_assert (ret == 0);
`0 == ret`

2021-07-21 15:31 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +  g_mutex_lock (&mutex);
Don't we need to init this at some point?

2021-07-22 01:56 UTC, rrcarlosrodriguez approved these changes

2021-07-22 15:25 UTC, emmadrigal approved these changes

2021-07-22 15:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxcontext.c
> +  g_mutex_lock (&mutex);
not when it is statically declared, according to [the docs](https://developer.gnome.org/glib/stable/glib-Threads.html#g-mutex-init):
> It is not necessary to initialize a mutex that has been statically allocated.

2021-07-22 22:04 UTC, closed without merging