Enhancement/refactor utils functions
TexasInstruments/edgeai-gst-plugins pull request #112
Opened 2021-09-27 01:16 UTC by jafet-chaves

2021-09-27 15:03 UTC, emmadrigal requested changes

2021-09-27 15:03 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +#include "gsttiovxbufferutils.h"
Who is `gsttiovxbufferutils.h`?

2021-09-27 15:03 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.h
> + * @info: Video information to be used as a reference for the pool
This isn't `info` this is `size`

2021-09-28 22:29 UTC, rrcarlosrodriguez requested changes

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
>  #include "gsttiovxutils.h"
Double check we actually need gsttiovxutils.h here

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.c
> +gst_tiovx_configure_pool (GstDebugCategory * category, GstBufferPool * pool,
You placed a message just before the function in the above 2 functions, let's be consistent and do the same for all the functions here and in all the other utils files

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferutils.c
> +
Let's be consistently putting a comment here

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferutils.h
> + * gst_tiovx_init_debug:
Wrong documentation

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +#include "gsttiovxbufferpoolutils.h"
Double check that we need all the utils headers here

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxpad.c
>  #include "gsttiovxutils.h"
Double check that we need all the utils headers here

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxsiso.c
>  #include "gsttiovxutils.h"
Double check that we need all the utils headers here

2021-09-28 22:29 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxtensorbufferpool.c
>  #include "gsttiovxutils.h"
Double check that we need all the utils headers here

2021-09-28 23:15 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
>  #include "gsttiovxutils.h"
Yes, because of the `vx_format_to_gst_format` function.

2021-09-28 23:28 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +#include "gsttiovxbufferpoolutils.h"
All utils files are required

2021-09-28 23:29 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxpad.c
>  #include "gsttiovxutils.h"
All utils files are required

2021-09-28 23:33 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxtensorbufferpool.c
>  #include "gsttiovxutils.h"
Yes, because of `gst_tiovx_empty_exemplar` the file "gsttiovxutils.h" is required for example

2021-09-29 19:59 UTC, emmadrigal approved these changes

2021-09-29 19:59 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.h
> +gst_tiovx_configure_pool (GstDebugCategory * category, GstBufferPool * pool, vx_reference * exemplar, GstCaps * caps, gsize size, guint num_buffers);
Don't go over 80 characters

2021-09-29 19:59 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferutils.c
> +static const gsize kcopy_all_size = -1;
standard is:
`copy_all_size`

2021-09-29 19:59 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferutils.c
> +  GstMemory *memory;
Initialize

2021-09-29 21:23 UTC, merged