Feature/add tiovxisp basic structure
TexasInstruments/edgeai-gst-plugins pull request #116
Opened 2021-09-29 21:02 UTC by jafet-chaves

2021-09-30 18:17 UTC, michaelgruner requested changes

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +#include "tiovx_viss_module.h"
Should this be a system path instead?

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +  "framerate = " GST_VIDEO_FPS_RANGE
align these backslashes

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +  "framerate = " GST_VIDEO_FPS_RANGE
align these backslashes

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +    GValue * value, GParamSpec * pspec);
This is not the standard for declaration. Did you use the indenter?

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +  self->dcc_config_file = NULL;
All instance variables should be initialized to a known state.

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +  }
1. This is not thread safe.
2. Maybe you want to take a look at [GST_PARAM_MUTABLE_READY](https://gstreamer.freedesktop.org/documentation/gstreamer/gstparamspec.html?gi-language=c). But I don't know if this actually performs any protection or it's just a nice way to display stuff on the inspect. See the `sink` property of the `glimagesink` for an example.

2021-09-30 18:17 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +  }
this can be reduced to simply `self->dcc_config_file = g_strdup (location);`. This will handle NULL gracefully.

2021-09-30 18:24 UTC, jafet-chaves commented on ext/tiovx/gsttiovxisp.c
> +#include "tiovx_viss_module.h"
I agree, it should be a system path but we are handling in this form everywhere else.

2021-10-04 16:22 UTC, emmadrigal approved these changes

2021-10-04 16:22 UTC, emmadrigal commented on ext/tiovx/gsttiovxisp.c
> +  g_return_val_if_fail (self, FALSE);
location pointer guard

2021-10-04 16:25 UTC, rrcarlosrodriguez approved these changes

2021-10-04 17:02 UTC, jafet-chaves commented on ext/tiovx/gsttiovxisp.c
> +  }
1. The gst_tiovx_isp_set_property calls GST_OBJECT_LOCK/GST_OBJECT_UNLOCK so the call to the function is already thread safe.
2. Using  GST_PARAM_MUTABLE_READY seems to add this protection already in the property, so there is no need to do the check in the function, see: https://github.com/GStreamer/gst-plugins-base/blob/master/gst/videorate/gstvideorate.c#L276

2021-10-04 17:22 UTC, merged