Feature/simo separate graph and node indexes
TexasInstruments/edgeai-gst-plugins pull request #118
Opened 2021-09-30 22:11 UTC by m-herrera

2021-09-30 22:29 UTC, emmadrigal requested changes

2021-09-30 22:29 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  priv->node_param_id = 0;
Initialize these to -1, this way we can know if it hasn't been initialized

2021-09-30 22:29 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (pad);
pointer guards for `graph_param_id` and `node_param_id`

2021-09-30 22:29 UTC, emmadrigal commented on ext/tiovx/gsttiovxmultiscaler.c
>    *input_ref = (vx_reference) self->obj.input.image_handle[0];
Rather than return the `input_ref` and the `output_refs` through pointers, let's also add these to the params being passed to the pad, this way we can ensure that node, graph, and exemplar always match.

`get_node_info` would have the following interface:
```
static gboolean
gst_tiovx_multi_scaler_get_node_info (GstTIOVXSimo * simo, vx_node * node,
    GstTIOVXPad * sink_pad, GList * src_pads)
```
And set and get params would be:
```
gst_tiovx_pad_set_params (GstTIOVXPad * pad, gint graph_param_id,
    gint node_param_id, vx_reference reference)
```
and 
```
void
gst_tiovx_pad_get_params (GstTIOVXPad * pad, gint * graph_param_id,
    gint * node_param_id, vx_reference *reference)
```

2021-09-30 22:29 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    i++;
`gst_tiovx_simo_process_graph` also uses the `graph_id` for queing and dequeing, ensure that this logic is also there

2021-10-05 14:15 UTC, emmadrigal approved these changes

2021-10-05 14:15 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (node_param_id);
`reference` pointer guard

2021-10-05 14:15 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.h
> + * @reference: (out) VX reference that this pad used for allocation
Pointer to the vx reference that this pad used for allocation

2021-10-05 16:36 UTC, rrcarlosrodriguez approved these changes

2021-10-05 16:36 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  g_return_if_fail (pad);
Check for reference, it can't be NULL

2021-10-05 20:16 UTC, merged