Feature/implement tiovxldc element
TexasInstruments/edgeai-gst-plugins pull request #121
Opened 2021-10-07 21:27 UTC by m-herrera

2021-10-07 22:00 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +#define SONY_IMX390_UB953_D3 0
This is never used, remove it

2021-10-07 22:01 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +#define TIOVX_LDC_SUPPORTED_FORMATS_SRC "{ GRAY8, GRAY16_LE, NV12, UYVY }"
Did you test all these formats?

2021-10-07 22:01 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +#define TIOVX_LDC_SUPPORTED_WIDTH "[1 , 8192]"
Did you test min and max resolutions?

2021-10-07 22:03 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +      "Changing the `dcc-file' property on tiovxldc when a file is open is not supported.");
Weird message, shouldn't we say `Changing the `dcc-file' property on tiovxldc is supported in NULL state only`

2021-10-07 22:04 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +  status = tiovx_init_sensor (sensorObj, self->sensor_name);
Deinit is never called

2021-10-07 22:05 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +  status = tiovx_init_sensor (sensorObj, self->sensor_name);
tiovx_deinit_sensor must be called in the deinit_module function, but also in this function in case an error happens after this. Single input-Single output pattern

2021-10-07 22:06 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +out:
Handle better errors here, you have to deinit the sensor is module_init fails

2021-10-07 22:06 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +  // target = target_id_to_target_name (self->target_id);
Implement target property

2021-10-07 22:08 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +out:
Deinit sensor here

2021-10-07 22:09 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +    vwidth = gst_structure_get_value (src_st, "width");
Put a TODO message here just to make sure we know where to add logic to enable different input/output resolutions (waiting for TI's input here)

2021-10-07 22:10 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxldc.c
> +static GstStaticPadTemplate src_template = GST_STATIC_PAD_TEMPLATE ("src_%u",
We have to limit the number of pads to create, We are not doing it yet

2021-10-07 22:36 UTC, jafet-chaves requested changes

2021-10-07 22:36 UTC, jafet-chaves commented on ext/tiovx/gsttiovxldc.c
> +}
This function will always return TRUE

2021-10-08 00:32 UTC, m-herrera commented on ext/tiovx/gsttiovxldc.c
> +#define TIOVX_LDC_SUPPORTED_FORMATS_SRC "{ GRAY8, GRAY16_LE, NV12, UYVY }"
I did, the original design included  YUYV but it is not supported by the tiovx node so I removed that one

2021-10-14 16:35 UTC, jafet-chaves commented on ext/tiovx/gsttiovxldc.c
> +  g_free (self->dcc_config_file);
Set to NULL after free

2021-10-14 20:07 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +static const int output_param_id_start = 7;
Please follow the standard chosen by the team. I can't recall if we were going to use macros or constants, but let's be consistent and avoid mixing them.

2021-10-14 20:10 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +gst_tiovx_ldc_set_dcc_file (GstTIOVXLDC * src, const gchar * location);
Follow the standard of the rest of the declarations.

2021-10-14 20:12 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +      "Filter",
Always check for existing similar elements in order to choose this. For example, if I inspect the `gleffects_fisheye` it suggests `Filter/Effect/Video` .

2021-10-14 20:13 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +
I suggest collapsing these spaces, these are related and is common to see them together.

2021-10-14 20:13 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +  self->num_src_pads = 0;
Initialize the object as well.

2021-10-14 20:14 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +  }
g_strdup supports NULL, so you can leave these part as simply `self->dcc_config_file = g_strudp (location)`.

2021-10-14 20:18 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +gst_tiovx_ldc_set_dcc_file (GstTIOVXLDC * self, const gchar * location)
Always use pointer guards of methods we create (and call) ourselves.

2021-10-14 20:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +      self->sensor_name = g_value_dup_string (value);
not how this is exactly what `gst_tiovx_ldc_set_dcc_file` does. It smells like refactoring.

2021-10-14 20:23 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +  status = tiovx_init_sensor (sensorObj, self->sensor_name);
This is not thread safe. protect `self->sensor_name`.

2021-10-14 20:24 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +    goto deinit_sensor;
I don't think deinit should be called if init failed.

2021-10-14 20:57 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +    gst_structure_set_value (src_st, "height", vheight);
Input and output resolutions are independent. We should return the full range instead.

2021-10-15 17:23 UTC, michaelgruner requested changes

2021-10-15 17:23 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +  "framerate = " GST_VIDEO_FPS_RANGE
These are exactly the same. Please use a single one.

2021-10-15 17:23 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +    GstStructure *src_st = gst_caps_get_structure (src_caps, 0);
How do you know this only has one structure? It may have several.

2021-10-15 17:23 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +    }
Why do you handle a special case when there is no intersection? if there is no intersection in one of the pads, we must fail (aka return the failed intersection).

2021-10-15 17:23 UTC, michaelgruner commented on ext/tiovx/gsttiovxldc.c
> +  src_caps = gst_caps_intersect (template_caps, sink_caps);
I don't like doing this intersection when the "width" and "height" fields haven't been removed. Right now is not problematic because we know both sink and src template overlap, but it may not be the case. I prefer taking a similar approach as you did with `get_sink_caps`.

2021-10-15 22:07 UTC, michaelgruner approved these changes

2021-10-15 22:07 UTC, michaelgruner commented on ext/tiovx/gsttiovxisp.c
> +  "height = " TIOVX_ISP_SUPPORTED_HEIGHT
Why did we remove the framerate. This sounds like a hack.

2021-10-15 22:36 UTC, merged