Feature/add multichannel support
TexasInstruments/edgeai-gst-plugins pull request #142
Opened 2021-11-10 00:17 UTC by emmadrigal

2021-11-11 14:02 UTC, jafet-chaves requested changes

2021-11-11 14:43 UTC, jafet-chaves requested changes

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmux.c
> +#define TIOVX_MUX_SUPPORTED_FORMATS_SRC "{RGB, RGBx, NV12, NV21, UYVY, YUY2, I420}"
Does this cover all possible formats supported by TIOVX? Should not be any? Should not the muxer handle any type of format?

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmux.c
> +    /* TODO */
Is this planned for a separate PR?

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmux.c
> +     * We'll remove the here, it will be readded as 1 when intersecting
readded -> read

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmux.c
> +   * We'll remove the here, it will be readded as 1 when intersecting
Again. readded -> read

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxdemux.c
> +#define TIOVX_DEMUX_SUPPORTED_FORMATS_SRC "{ RGB, RGBx, NV12, NV21, UYVY, YUY2, I420 }"
Should not muxer and demuxer use ANY caps?

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxdemux.c
> +   * We'll remove the here, it will be readded as 1 when intersecting
readded -> read

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxdemux.c
> +  GstClockTime pts, dts, duration;
Should these be inititalized?

2021-11-11 14:43 UTC, jafet-chaves commented on ext/tiovx/gsttiovxdemux.c
> +    /* What to do if number of pads is different? */
is this a TODO? If so mark it as one

2021-11-15 18:00 UTC, rrcarlosrodriguez requested changes

2021-11-15 18:00 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxdemux.c
> +#define TIOVX_DEMUX_SUPPORTED_FORMATS_SRC "{ RGB, RGBx, NV12, NV21, UYVY, YUY2, I420 }"
it shouldn't, but it should take TENSOR caps into consideration

2021-11-16 16:36 UTC, michaelgruner requested changes

2021-11-16 16:36 UTC, michaelgruner commented on ext/tiovx/gsttiovxdemux.c
> +      filter = intersect_with_template_caps (filter, pad);
If we are doing this here, maybe we can remove it from the internal `get_XXX_caps` methods?

2021-11-16 16:36 UTC, michaelgruner commented on ext/tiovx/gsttiovxdemux.c
> +    /* What to do if number of pads is different? */
Well, if the caps negotiation went well, this should be impossible. I'd treat this as a programming error and use an assertion.

2021-11-16 16:36 UTC, michaelgruner commented on ext/tiovx/gsttiovxdemux.c
> +  buffer_list = g_malloc0 (sizeof (GstBuffer *) * num_pads);
If the 16 limit is true, I'd very much rather you use a static array like `GstBuffer buffer_list[MAX_BUFFERS]`

2021-11-16 16:36 UTC, michaelgruner commented on ext/tiovx/gsttiovxdemux.c
> +    buffer_list[i] = gst_buffer_new ();
Wait, but this buffer is empty? We most definitely need it to be mappable, otherwise it won't be usable by SW elements.

2021-11-16 16:36 UTC, michaelgruner commented on ext/tiovx/gsttiovxdemux.c
> +  while (NULL != pads_sublist) {
Can we use a for loop here?

2021-11-16 16:36 UTC, michaelgruner commented on ext/tiovx/gsttiovxdemux.h
> + * GST_IS_TIOVX_DEMUX:
This documentation is wrong.

2021-11-17 20:36 UTC, emmadrigal commented on ext/tiovx/gsttiovxdemux.c
> +#define TIOVX_DEMUX_SUPPORTED_FORMATS_SRC "{ RGB, RGBx, NV12, NV21, UYVY, YUY2, I420 }"
We'll consider TENSOR caps in a latter PR

2021-11-17 20:37 UTC, emmadrigal commented on ext/tiovx/gsttiovxdemux.c
> +#define TIOVX_DEMUX_SUPPORTED_HEIGHT "[1 , 8192]"
Yes, we need to create a vx_image for this TI's framework limits us. This is also the upper limit of the requirement for  image size

2021-11-17 20:37 UTC, emmadrigal commented on ext/tiovx/gsttiovxdemux.c
> +#define TIOVX_DEMUX_SUPPORTED_CHANNELS "[1 , 16]"
This is a limitation of the modules,

2021-11-17 20:40 UTC, emmadrigal commented on ext/tiovx/gsttiovxdemux.c
> +  }
This was incorrectly copied from the SIMO where we need to check for the subclasses' template. I'll remove this

2021-11-17 20:48 UTC, emmadrigal commented on ext/tiovx/gsttiovxdemux.c
> +   * We'll remove the here, it will be readded as 1 when intersecting
readded: to add again

2021-11-17 20:52 UTC, emmadrigal commented on ext/tiovx/gsttiovxdemux.c
> +   */
The source caps are fixed to 1 in the template. Since we removed them on the sink_caps when intersecting them in the template it will be added

2021-11-17 21:18 UTC, emmadrigal commented on ext/tiovx/gsttiovxmux.c
> +#define TIOVX_MUX_SUPPORTED_FORMATS_SRC "{RGB, RGBx, NV12, NV21, UYVY, YUY2, I420}"
It can't handle any format since we can't create vx_images for any format

2021-11-17 21:18 UTC, emmadrigal commented on ext/tiovx/gsttiovxmux.c
> +  "video/x-raw, "                                            \
Tensor's will be supported in a following feature

2021-11-17 21:22 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmuxmeta.c
> +      { GST_META_TAG_VIDEO_STR, GST_META_TAG_MEMORY_STR, NULL };
Yes this would be used by SW elements

2021-11-25 17:31 UTC, michaelgruner requested changes

2021-11-25 17:31 UTC, michaelgruner commented on ext/tiovx/gsttiovxmux.c
> +GstCaps *
static

2021-11-25 17:31 UTC, michaelgruner commented on ext/tiovx/gsttiovxmux.c
> +}
I feel this method is unnecessary. Is it really doing anything?

2021-11-25 20:51 UTC, emmadrigal commented on ext/tiovx/gsttiovxmux.c
> +  vxReleaseReference (&pad->exemplar);
The reference is zeroed after calling [vxReleaseReference](https://www.khronos.org/registry/OpenVX/specs/1.1/html/dd/d90/group__group__reference.html#gadd23893e169c3da18b5618b671c3e3f2)

2021-11-25 21:12 UTC, emmadrigal commented on ext/tiovx/gsttiovxmux.c
> +}
It is indeed unnecessary

2021-12-13 13:36 UTC, emmadrigal commented
This branch has been merged into `develop` as part of #160

2021-12-13 13:36 UTC, closed without merging