Feature/support background as property on tiovxmosaic
TexasInstruments/edgeai-gst-plugins pull request #143
Opened 2021-11-10 21:37 UTC by dchvs

2021-11-11 14:07 UTC, emmadrigal requested changes

2021-11-11 14:07 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  memcpy ((void *) *addr, (const void *) file_buffer, planes_offset);
You can't just copy the memory 1:1.  If the stride doesn't match the width the output will be incorrect.

See the following logic:
https://github.com/TexasInstruments/edgeai-tiovx-modules/blob/main/test/app_common.c#L1415

2021-11-11 14:07 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  fread (file_buffer, 1, file_size, background_img_file);
Is there a need for this to be TI memory? the output `addr` is already TI memory

2021-11-11 14:07 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +
pointer guard

2021-11-11 14:07 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +gst_tiovx_mosaic_has_background (const gchar * background)
inacurate name

2021-11-11 14:14 UTC, jafet-chaves requested changes

2021-11-11 14:14 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +#define MODULE_MAX_NUM_PLANES 4
Keep the standard on new code: static const int

2021-11-11 14:14 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +#define DEFAULT_TIOVX_MOSAIC_BACKGROUND ""
Keep the standard on new code: static const int

2021-11-11 14:14 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  ret = (0 != g_strcmp0 ("", background)) ? TRUE : FALSE;
Before this it is missing pointer guard for background

2021-11-11 14:14 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +gst_tiovx_mosaic_allocate_single_user_data_object (GstTIOVXMosaic * self,
Missing pointer guards for function that we define and create

2021-11-19 17:52 UTC, dchvs commented on ext/tiovx/gsttiovxmosaic.c
> +#define MODULE_MAX_NUM_PLANES 4
This variable is meant to initialize a pointer of arrays. Therefore it cannot be `static const int` in C, because it will give Variable Length Array (VLA) error by default. See https://www.keil.com/support/man/docs/armcc/armcc_chr1359124950297.htm.

2021-11-19 19:46 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +vx_uint32 *gst_tiovx_mosaic_learn_planes_offsets (GstTIOVXMosaic * self,
I propose the following function name:
`gst_tiovx_mosaic_compute_planes_offsets`

2021-11-19 19:47 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +/*static*/ vx_uint32 *
Remove commented code

2021-11-19 19:47 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +gst_tiovx_mosaic_learn_planes_offsets (GstTIOVXMosaic * self, vx_image img)
I dont understand this, it does not seem be doing anything useful

2021-11-19 20:03 UTC, jafet-chaves approved these changes

2021-11-22 14:41 UTC, emmadrigal requested changes

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  self->user_data_allocator = g_object_new (GST_TYPE_TIOVX_ALLOCATOR, NULL);
You are never calling `g_object_unref` on this object

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  g_return_val_if_fail (self, FALSE);
memory, background_img pointer guards

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  gint h = 0;
Use more representative names, `width`, and `height` are much better

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  if (!*memory) {
`NULL == *memory` is how we are checking for null pointers

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    status =
Do you need to make this for very plane?

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +      file_buffer = (char *) file_buffer + planes_offset;
This check should be outside of this loop, you just need to copy image_size from file to `addr[0]` once since memory is contiguous between planes

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +      stride_length = image_addr.dim_y / image_addr.step_y;
This is not stride lenght. Plane rows is what you are looking for

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +      /* Return pointer to plain base */
Typo `plane`

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +gst_tiovx_mosaic_allocate_user_data_objects (GstTIOVXMosaic * self)
You are not allocating any [user data objects](https://software-dl.ti.com/jacinto7/esd/processor-sdk-rtos-jacinto7/latest/exports/docs/tiovx/docs/user_guide/vx__khr__user__data__object_8h.html#a863903e2890171d914598216e0727d73) in this function. Change the name to something more accurate

2021-11-22 14:41 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +gst_tiovx_mosaic_allocate_background_image (GstTIOVXMosaic * self,
This function can have a better name, you are not only allocating the memory, but also loading the data to the memory

2021-11-23 15:41 UTC, dchvs commented on ext/tiovx/gsttiovxmosaic.c
> +    status =
It's because of the VX image patch that iterates per plane index. See the `plane_index: vx_uint32` parameter below: 

`VX_API_ENTRY vx_status VX_API_CALL vxMapImagePatch(vx_image image, const vx_rectangle_t *rect, vx_uint32 plane_index, vx_map_id *map_id, vx_imagepatch_addressing_t *addr, void **ptr, vx_enum usage, vx_enum mem_type, vx_uint32 flags);`

2021-11-23 15:42 UTC, dchvs commented on ext/tiovx/gsttiovxmosaic.c
> +  g_return_val_if_fail (self, FALSE);
These are outputs parameters

2021-11-24 23:57 UTC, emmadrigal requested changes

2021-11-24 23:57 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  g_return_val_if_fail (self, FALSE);
`*memory` is an output paramter, `memory` is an input
also background_img is a pointer who also needs a pointer guard

2021-11-24 23:57 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    rectangle.end_y = height;
Rectangle doesn't change between planes, there is no need to set it every iteration

2021-11-24 23:57 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +        &file_buffer, VX_WRITE_ONLY, VX_MEMORY_TYPE_HOST, VX_NOGAP_X);
`file_buffer` is the wrong name for this variable, it comes from the memory rather than disk

2021-11-24 23:57 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +        memcpy ((void *) addr[i], (const void *) file_buffer, width_per_plane);
Why are we still performing the copy twice?
`fread (addr[i], 1, plane_sizes[i], background_img_file);` 
whould work withtout having an intermediate file_buffer

2021-11-24 23:57 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +      fread (addr[i], 1, plane_sizes[i], background_img_file);
This check should be performed outside the plane loop, we should just copy once from:
background_img_file to addr[0] with a size of data_size/file_size

2021-11-24 23:57 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +        file_buffer = (char *) file_buffer + width_per_plane;
This `file_buffer` is being overwritten on every frame

2021-11-30 14:23 UTC, emmadrigal requested changes

2021-11-30 14:23 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  }
Since you created this during the `init` this should be unrefed during the `finalize`.

If after moving it, OpenVX has some unreleased memory due to the sequence you can leave it here

2021-11-30 14:23 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +        &img_buffer, VX_WRITE_ONLY, VX_MEMORY_TYPE_HOST, VX_NOGAP_X);
This can be moved inside the `data_size != file_size` if

2021-11-30 18:06 UTC, emmadrigal approved these changes

2021-11-30 18:13 UTC, merged