Exit plugin execution gently when blocksize from upstream is invalid
TexasInstruments/edgeai-gst-plugins pull request #147
Opened 2021-11-19 19:38 UTC by dchvs

2021-11-19 19:59 UTC, jafet-chaves approved these changes

2021-11-22 14:44 UTC, emmadrigal requested changes
Aren't you missing the case for SISO?

2021-11-22 14:44 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +  if (tmp_buffer != *buffer && tmp_buffer) {
Separate logic blocks with parenthesis
`(tmp_buffer != *buffer) && tmp_buffer`

2021-11-22 16:53 UTC, rrcarlosrodriguez approved these changes

2021-11-22 21:54 UTC, emmadrigal approved these changes

2021-11-22 21:54 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (inbuf, ret);
These pointer guards aren't necessary since this function is called from GStreamer, remove them

2021-11-23 01:05 UTC, merged