Draft/add multichannel support to siso
TexasInstruments/edgeai-gst-plugins pull request #148
Opened 2021-11-22 16:45 UTC by emmadrigal

2021-11-24 21:33 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmux.c
> +        &pad->buffer_pool, in_buffer, &pad->exemplar, caps, pad->pool_size, 1);
Should `num_channels` be hardcoded here?

2021-11-24 22:08 UTC, emmadrigal commented on ext/tiovx/gsttiovxmux.c
> +        &pad->buffer_pool, in_buffer, &pad->exemplar, caps, pad->pool_size, 1);
Mux always has a single channel in the input

2021-12-01 20:47 UTC, rrcarlosrodriguez requested changes

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxcolorconvert.c
> +  "num-channels = " TIOVX_COLOR_CONVERT_SUPPORTED_CHANNELS
batch-size is a better name, I know TI uses num-channels but from user perspective it might be confusing

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxcolorconvert.c
> +  colorconvert->num_channels = num_channels;
DEFAULT_NUM_CHANNELS is not used anymore, remove the macro definition

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  if (0 != num_channels) {
I don't understand this, why don't you just use num_channels = 1 (instead of 0) when using 1 channel

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> -    goto error;
Why are you removing this goto error?

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.c
> +    guint num_buffers, vx_reference * exemplar, gsize size, gint num_channels,
Pointer guard for num_channels, it is a gint so values less than 0 shouldn't be allowed by the function

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.c
> +    gint num_channels)
Same pointer guard here

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.h
> + * gst_tiovx_buffer_pool_config_set_num_channels:
get_num_channels

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpoolutils.h
> + * @channels: Number of channels that each buffer will have
num_channels

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferutils.c
> +    GstCaps * caps, guint pool_size, gint num_channels)
Same pointer guard here

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferutils.h
> +    gint num_channels);
Document this new parameter

2021-12-01 20:47 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmeta.h
> + * @array_lenght: Number of channels for this buffer
length

2021-12-01 21:16 UTC, michaelgruner approved these changes

2021-12-02 14:30 UTC, emmadrigal commented on ext/tiovx/gsttiovx.c
> +  // ret = gst_element_register (plugin, "tiovxdlcolorblend", GST_RANK_NONE,
This PR only enables colorconvert. Other elememtns will be added in further PRs

This changes won't be merged into the develop branch until all elements have been merged

2021-12-02 14:30 UTC, emmadrigal commented on ext/tiovx/gsttiovxcolorconvert.c
> +  "num-channels = " TIOVX_COLOR_CONVERT_SUPPORTED_CHANNELS
I agree, but I think it might be confusing to change it only for us.

2021-12-02 14:32 UTC, emmadrigal commented on ext/tiovx/meson.build
> +  # 'gsttiovxdlcolorblend.c',
All elements except for colorconvert have been disabled for this PR. Other elements will be added in further PRs.

This changes won't be merged until all elements have been readded

2021-12-02 14:34 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  if (0 != num_channels) {
0 will be returned from the bufferpool when the value can't be found in the caps or the bufferpool configuration

2021-12-02 14:35 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> -    goto error;
This was mistakenly removed.

2021-12-02 14:50 UTC, merged