Pop processed buffers only
TexasInstruments/edgeai-gst-plugins pull request #151
Opened 2021-11-30 19:22 UTC by m-herrera

This avoids popping buffers that were not processed

2021-11-30 20:17 UTC, emmadrigal approved these changes

2021-11-30 20:22 UTC, jafet-chaves approved these changes

2021-12-16 23:24 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  GstClockTime output_start_time, output_end_time;
Initialize to `GST_CLOCK_TIME_NONE`

2021-12-16 23:27 UTC, emmadrigal approved these changes

2021-12-16 23:27 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  gst_video_info_from_caps (&priv->src_info, caps);
It isn't an issue now, since both colorblend and mosaic have a `video/x-raw` output, but we should leave a TODO/issue to improve this, since we could have a `tensor` output which won't work with `gst_video_info_from_caps`

2021-12-17 18:03 UTC, rrcarlosrodriguez requested changes

2021-12-17 18:03 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxmosaic.c
> +        self->sink_has_caps = FALSE;
You can avoid resetting this, refactor the logic

2021-12-17 18:03 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  GstVideoInfo src_info;
I don't like hardcoding the MISO to video here, is there another way to solve this?

2021-12-17 18:03 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (GST_VIDEO_INFO_FPS_N (&priv->src_info) == 0) {
What is the plan to make this logic work with tensor caps? This looks really hardcoded to video and I don't like it

2021-12-20 13:43 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  self = GST_TIOVX_MOSAIC (agg);
This is a Gstreamer function, we don't need a pointer guard for `agg`

2022-02-01 22:56 UTC, emmadrigal requested changes

2022-02-01 22:56 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    // Keep a reference to the src caps videoinfo
Use `/* */` commenting style

2022-02-01 22:56 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  /* The segment position most be updated after the aggregator finish buffer
Typo `must`

2022-02-01 22:56 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +      if (-1 == tmp_pts || -1 == tmp_duration) {
Use `GST_CLOCK_TIME_NONE` instead of `-1`

2022-02-01 22:56 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +/* Mark all processed buffers as read  */
watch the indentation

2022-02-02 20:47 UTC, emmadrigal approved these changes

2022-02-02 20:47 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  if (self->nframes != 0) {
`0 != self->nframes`

2022-02-02 20:47 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  if (segment->position == -1 || segment->position < segment->start) {
`-1 == segment->position`

2022-02-02 20:47 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  if (self->nframes == 0) {
`0 == self->nframes`

2022-02-02 20:47 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  if (GST_VIDEO_INFO_FPS_N (&self->src_info) == 0) {
`0 == GST_VIDEO_INFO_FPS_N (&self->src_info)`

2022-02-02 20:47 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  if (segment->stop != -1) {
`-1 != segment->stop`

2022-02-02 20:47 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    for (l = GST_ELEMENT (agg)->sinkpads; l != NULL; l = g_list_next (l)) {
`    for (l = GST_ELEMENT (agg)->sinkpads; NULL != l; l = g_list_next (l)) {`

2022-02-02 20:47 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +
Is there a reason for this empty line?

2022-02-03 22:57 UTC, merged