Add the GstTIOVXMux AppSrc & AppSink handling pipeline
TexasInstruments/edgeai-gst-plugins pull request #153
Opened 2021-12-06 22:54 UTC by dchvs

2021-12-06 23:04 UTC, emmadrigal requested changes

2021-12-06 23:04 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +                print("New sinker buffer emition");
`;` is unnecessary

2021-12-06 23:04 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +                print("Installed the sinker user callback");
`;` is unnecessary

2021-12-06 23:04 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +gsttiovx_mux_appsrc_app_desc = "appsrc is-live=true name=appsrc do-timestamp=true format=time ! video/x-raw,format=RGB,width=320,height=240,framerate=30/1,pixel-aspect-ratio=1/1 ! videoconvert ! vide
These lines are too long, split them into multiple lines
https://cppsecrets.com/users/77661151141051181051151041101171219711410897103971001009764103109971051084699111109/Breaking-a-Long-string-into-multiple-lines.php

2021-12-06 23:04 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +                        raise GstMediaError("Unable to install sinker buffers emitter callback")
`raise ... from e`
Otherwise you loose information from the other exception

2021-12-06 23:04 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +                time.sleep(25)
25 is a magic number

2021-12-06 23:04 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +                        timeout = 2 * 1000000000
2 is a magic number
`1000000000` is better as a `SECONDS_TO_NANOSECONDS` global

2021-12-06 23:05 UTC, emmadrigal commented
This branch can't go to develop since the mux element isn't supported in develop yet

2021-12-07 14:44 UTC, jafet-chaves commented on tests/examples/test_mux_app.py
> +class TestBuferingMaster(unittest.TestCase):
This is minor but Bufering goes with double f: "Buffering"

2021-12-07 14:45 UTC, jafet-chaves commented on tests/examples/test_mux_app.py
> +        def setUp(self):
There is a mix of letter casing standards in this code. Please stick with one.

2021-12-07 15:09 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +from unittest.mock import MagicMock
For python we always follow pep8: https://www.python.org/dev/peps/pep-0008/#imports

2021-12-08 17:21 UTC, dchvs commented on tests/examples/test_mux_app.py
> +        def setUp(self):
In this particular case, the `setUp()` method instead of `set_up()`, comes from the Framework testing convention. Please check out at: https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUp

2021-12-08 20:00 UTC, emmadrigal requested changes

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +        appsink name=appsink sync=true emit-signals=true drop=true max-buffers=2""" % (get_caps_parameters())
Keep the start of the line aligned
Keep the `\` aligned if possible

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +        kmssink force-modesetting=true sync=false async=false""" % (get_caps_parameters())
Keep the start of the line aligned
Keep the \ aligned if possible

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +import time
`time` is unused

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +        ret, current, pending = self._pipeline.get_state(gst.CLOCK_TIME_NONE)
pending is unused, replace by:
```
         ret, current, _ = self._pipeline.get_state(gst.CLOCK_TIME_NONE) ```

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +    def _sinker_callback_buffers_emitter(self, obj_sinker, data):
`data` is unused, do you need it for the function definition? otherwise removeit

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/test_mux_app.py
> +gsttiovx_mux_appsrc_app_desc = """\
naming for constants should be in `UPPER_CASE`

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/setup.py
> +dev_requires = ["pre-commit"]
constants should be `UPPER_CASE`

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/setup.py
> +            logging.warning("Unable to run 'pre-commit install'")
This is too general, according to the documentation this function only raises `CalledProcessError` only make the try catch for that case

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/setup.py
> +from codecs import open
`open` is unused

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/setup.py
> +import os
`os` is unused

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/setup.py
> +import unittest
`unittest` is unused

2021-12-08 20:00 UTC, emmadrigal commented on tests/examples/setup.py
> +from setuptools.command.develop import develop
`setuptools` is a non-standard library, it should be in another section

2023-07-07 23:26 UTC, closed without merging