Feature/add multichannel support to tensor elements
TexasInstruments/edgeai-gst-plugins pull request #154
Opened 2021-12-06 22:55 UTC by emmadrigal

2021-12-07 15:07 UTC, jafet-chaves approved these changes

2021-12-07 18:16 UTC, rrcarlosrodriguez requested changes

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.h
> + * gst_tiovx_exemplar_from_caps:
What about: `gst_tiovx_get_exemplar_from_caps??` to keep consistency with the other functions in the utils

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +  /* Image */
Where are the pointer guards?

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +      return FALSE;
Why FALSE? This function returns a vx_reference

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +      return FALSE;
Same here

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +      return FALSE;
Same here

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +        return FALSE;
Same here

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on tests/check/meson.build
> +  # ['libs/gsttiovxsimo', false, [gst_internal_dep],  [] ],
Don't deactivate this tests

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on tests/check/meson.build
> +  # ['libs/gsttiovxmiso', false, [gst_internal_dep],  [] ],
Don't deactivate this tests

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +      return FALSE;
Same here

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +     * The only way to distinguish these two caps is by the precense of channel-order
typo: presence

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +     * in dlpreproc's caps
Why are you referring to dlpreproc here in the utils? we shouldn't do that

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> -  klass->get_size_from_caps =
If we are not using these functions anymore, delete them from the .h as well

2021-12-07 18:16 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxmux.c
> +      GST_ERROR_OBJECT (self, "current caps: %" GST_PTR_FORMAT, caps);
Why ERROR? Change to INFO or DEBUG

2021-12-08 20:03 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +    /* Currently colorblend supports a single channel and dlpreproc 3.
This is a fixed on the modules side

2021-12-08 23:12 UTC, merged