Feature/colorconvert negotiation issues
TexasInstruments/edgeai-gst-plugins pull request #19
Opened 2021-07-27 23:19 UTC by emmadrigal

2021-07-27 23:55 UTC, rrcarlosrodriguez approved these changes

2021-07-28 14:08 UTC, jafet-chaves approved these changes

2021-07-28 21:48 UTC, michaelgruner requested changes

2021-07-28 21:48 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxpad.c
> +      gst_buffer_pool_set_active (GST_BUFFER_POOL (pool), TRUE);
This feels strange here. I don't feel this is the place for this. The pool should be activated right after it is created and configured.

2021-07-29 15:23 UTC, michaelgruner approved these changes

2021-07-29 15:44 UTC, merged