DRAFT: Feature/implement vx pyramid pool
TexasInstruments/edgeai-gst-plugins pull request #192
Opened 2022-02-16 22:58 UTC by m-herrera

2022-02-24 23:54 UTC, emmadrigal requested changes
You are still missing pyramid case in `get_exemplar_from_caps`

2022-02-24 23:54 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferutils.c
> +#include <math.h>
what do we need math for?

2022-02-25 15:58 UTC, rrcarlosrodriguez requested changes

2022-02-25 15:58 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxpyramidbufferpool.c
> +  gst_buffer_add_tiovx_pyramid_meta (buffer, exemplar, num_channels,
Pointer guards

2022-02-25 15:58 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxpyramidbufferpool.c
> +    GstBuffer * buffer)
Pointer guards

2022-02-25 15:58 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxpyramidmeta.h
> +#define MODULE_MAX_NUM_PYRAMIDS (8u)
Does this mean the maximum number of levels is 8? if so, we need to take this into consideration in the caps negotiation

2022-02-25 15:58 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxpyramidbufferpool.c
> +
As discussed, for levels we should take into consideration the resolution as well, to avoid reaching the minimum or invalid levels for a specific resolution.

2022-03-01 17:28 UTC, m-herrera commented on gst-libs/gst/tiovx/gsttiovxpyramidmeta.h
> +#define MODULE_MAX_NUM_PYRAMIDS (8u)
It does, the pyramid element specification says up to 32 but the module's test sets a maximum of 8

2022-03-09 00:17 UTC, emmadrigal approved these changes

2022-03-09 00:17 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpyramidbufferpool.h
> +G_DECLARE_FINAL_TYPE(GstTIOVXPyramidBufferPool, gst_tiovx_pyramid_buffer_pool, GST_TIOVX, PYRAMID_BUFFER_POOL, GstTIOVXBufferPool);
This line is too long, try to stick to a max of 80 characters

2022-03-09 00:17 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxpyramidbufferpool.h
> +#endif // __GST_TIOVX_PYRAMID_BUFFER_POOL_H__
Use `/* ANSI style comments */`

2022-03-09 16:09 UTC, merged