Feature/implement pyramid element
TexasInstruments/edgeai-gst-plugins pull request #203
Opened 2022-03-08 22:44 UTC by m-herrera

2022-03-09 00:34 UTC, emmadrigal requested changes

2022-03-09 00:34 UTC, emmadrigal commented on ext/tiovx/gsttiovx.c
> +
Why did you move this up? this change should be a part of your PR

2022-03-09 00:34 UTC, emmadrigal commented on ext/tiovx/gsttiovxpyramid.c
> +      "Converts video frames to a vx_pyramid representation using the TIOVX Modules API",
Not `vx_pyramid` we are abstracting the OpenVX implementation through the modules and then through our own modules, the user shouldn't need to know that this is a vx_pyramid. Just `pyramid` should be fine

2022-03-09 00:34 UTC, emmadrigal commented on ext/tiovx/gsttiovxpyramid.c
> +  pyramid->output.bufq_depth = num_channels;
Move these to the `Configure input` and `Configure output` sections

2022-03-09 00:34 UTC, emmadrigal commented on ext/tiovx/gsttiovxpyramid.c
> +    }
Shouldn't we fail on the `else` case?

2022-03-09 00:34 UTC, emmadrigal commented on ext/tiovx/gsttiovxpyramid.c
> +
pointer guards

2022-03-09 15:02 UTC, m-herrera commented on ext/tiovx/gsttiovx.c
> +
I moved it to keep the alphabetical order

2022-03-09 15:51 UTC, m-herrera commented on ext/tiovx/gsttiovxpyramid.c
> +    }
I added a debug message indicating that there were no current caps on the src pad, but I don't think it is necessary to fail since it can still transform the caps based on the template

2022-03-10 23:13 UTC, rrcarlosrodriguez requested changes

2022-03-10 23:13 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxpyramid.c
> +#define TIOVX_PYRAMID_SUPPORTED_WIDTH "[1 , 1920]"
Same here

2022-03-14 23:57 UTC, m-herrera commented on ext/tiovx/gsttiovxpyramid.c
> +    }
I removed the validation altogether, since gst_pad_peer_query_caps is never NULL as seen [here](https://gstreamer.freedesktop.org/documentation/gstreamer/gstpad.html?gi-language=c#gst_pad_peer_query_caps)

2022-03-15 15:02 UTC, emmadrigal approved these changes

2022-03-15 15:02 UTC, emmadrigal commented on ext/tiovx/gsttiovxpyramid.c
> +    gst_caps_unref (current_caps);
`current_caps = NULL`

2022-03-15 15:02 UTC, emmadrigal commented on ext/tiovx/gsttiovxpyramid.c
> +    gst_caps_unref (tmp);
`tmp = NULL`

2022-03-15 15:45 UTC, merged