Feature/dof viz sde
TexasInstruments/edgeai-gst-plugins pull request #222
Opened 2022-06-16 11:54 UTC by ravi-rahul

Adding dof viz, sde and sde viz plugins
please review

2022-06-20 15:14 UTC, emmadrigal requested changes

2022-06-20 15:14 UTC, emmadrigal commented on ext/tiovx/gsttiovxdofviz.c
> +          MIN_THRESHOLD, MAX_THRESHOLD, DEFAULT_THRESHOLD, G_PARAM_READWRITE));
If this can't change during playing it should also be GST_PARAM_MUTABLE_READY

2022-06-20 17:52 UTC, m-herrera requested changes

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +    {TIVX_MAX_DISPARITY_191, "disparity_min +191", "disparity_max_191"},
Use same spacing for all of these

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +  "num-channels = " TIOVX_SDE_SUPPORTED_CHANNELS
Align "\" here as well

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +      "Sde using the TIOVX Modules API", "Rahul T R <r-ravikumar@ti.com>");
Standardize this between elements

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +    sde->input_left.bufq_depth = num_channels;
set bufq_depth to 1

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +    sde->input_right.bufq_depth = num_channels;
set bufq_depth to 1

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +  sde->output.bufq_depth = num_channels;
set bufq_depth to 1

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +    sink_caps_copy = gst_caps_copy (sink_caps);
Duplicated copy

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +
remove empty spaces

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +  self->vis_confidence = DEFAULT_VIZ_CONFIDENCE;
Standardize vis or viz

2022-06-20 17:52 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +  sdeviz->output.bufq_depth = num_channels;
set bufq_depth to 1

2022-06-22 12:48 UTC, ravi-rahul commented on ext/tiovx/gsttiovxsdeviz.c
> +
can you please clarify this

2022-06-29 14:21 UTC, ravi-rahul commented
Dof test Pipeline:

**_gst-launch-1.0 v4l2src io-mode=2 device=/dev/video2 ! image/jpeg, width=1280, height=720 ! jpegdec ! tiovxdlcolorconvert ! video/x-raw, format=NV12 ! tiovxpyramid ! application/x-pyramid-tiovx, format=GRAY8 ! tee name=split ! queue ! tiovxdof name=dof ! tiovxdofviz ! kmssink sync=false -v split. ! tiovxdelay delay-size=1 ! dof.delayed_sink_**

2022-06-29 18:19 UTC, m-herrera requested changes

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +                                                  "minimum_disparity_minus_3"},
This indentation seems off, I'll provide the indentation script, please apply it to all the files

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +  "num-channels = " TIOVX_SDE_VIZ_SUPPORTED_CHANNELS
Align \ characters

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +struct _GstTIOVXSdeviz
Replace with GstTIOVXSde**V**iz

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +
I meant to remove the empty line so that all declarations are consistent with spacing

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +  gstbasetransform_class->transform_ip_on_passthrough = FALSE;
Smae as before

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +
Add pointer guard for context

2022-06-29 18:19 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +  if (!gst_video_info_from_caps (&video_info1, caps1)) {
This only support one pad direction, if caps are sde I think this would not work. Same as before

2022-07-04 08:07 UTC, ravi-rahul commented on ext/tiovx/gsttiovxsdeviz.c
> +
Can you please clarify this

You mean 
(vx_context) context ?

Why is this necessary?

2022-07-07 15:43 UTC, m-herrera approved these changes

2022-07-07 15:43 UTC, m-herrera commented on ext/tiovx/gsttiovxdofviz.c
> +  /* Compare tensor fields if sink pad */
These are not tensors

2022-07-07 15:43 UTC, m-herrera commented on ext/tiovx/gsttiovxsdeviz.c
> +  gstbasetransform_class->transform_ip_on_passthrough = FALSE;
Please remove these since the element can't have the same caps on sink and src

2022-07-07 15:43 UTC, m-herrera commented on ext/tiovx/gsttiovxsde.c
> +    gst_caps_unref (caps);
If the condition is met, the` goto exit` will be called and the caps object won't be unreferenced

2022-07-08 05:03 UTC, merged