Feature/tiovxmemalloc element
TexasInstruments/edgeai-gst-plugins pull request #223
Opened 2022-06-21 00:03 UTC by m-herrera

2022-06-21 00:36 UTC, rrcarlosrodriguez requested changes
Changes requested.

2022-06-21 00:36 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovx.c
> +#include "gsttiovxmemalloc.h"
Alphabetical order

2022-06-21 00:36 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxmemalloc.c
> +  PROP_IN_POOL_SIZE,
Change to pool size, because we are creating only 1 pool. Same for the property

2022-06-21 00:36 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxmemalloc.c
> +  self->in_caps = gst_caps_copy (incaps);
self->caps

2022-06-22 20:02 UTC, emmadrigal requested changes

2022-06-22 20:02 UTC, emmadrigal commented on ext/tiovx/gsttiovxmemalloc.c
> +    GST_ERROR_OBJECT (self, "Failed to get size from input");
you need to release `exemplar` in this case

2022-06-22 20:02 UTC, emmadrigal commented on ext/tiovx/gsttiovxmemalloc.c
> +    GST_ERROR_OBJECT (self, "Failed to add new pool in propose allocation");
you need to release `exemplar` in this case

2022-06-22 20:02 UTC, emmadrigal commented on ext/tiovx/meson.build
> +  'gsttiovxmemalloc.h',
alphabetical order

2022-06-22 20:02 UTC, emmadrigal commented on ext/tiovx/meson.build
> +  'gsttiovxmemalloc.c',
alphabetical order

2022-06-28 22:11 UTC, rrcarlosrodriguez approved these changes

2022-06-29 04:53 UTC, merged