Add base structure for the MISO element
TexasInstruments/edgeai-gst-plugins pull request #36
Opened 2021-08-04 20:19 UTC by emmadrigal

2021-08-04 20:21 UTC, emmadrigal commented
This PR includes:
* the base TIOVX Mosi structure
* Downstream allocation
* Basic testing for pushing buffers

2021-08-04 23:04 UTC, jafet-chaves requested changes

2021-08-04 23:04 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  GList *l;
Initialize

2021-08-04 23:04 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    GstCaps *caps = NULL;
Do you need to call unref on this GstCaps?

2021-08-06 14:50 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    GstCaps *caps = NULL;
`query_parse_allocation` is transfer none: https://gstreamer.freedesktop.org/documentation/gstreamer/gstquery.html?gi-language=c#gst_query_parse_allocation

2021-08-09 23:09 UTC, rrcarlosrodriguez requested changes

2021-08-09 23:09 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +#include "gsttiovxmeta.h"
This one is not used here

2021-08-09 23:09 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +#include <app_init.h>
Is this used here?

2021-08-09 23:09 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  guint out_pool_size;
Can we handle the output pool size as the input pads? as part of the GstTIOVXPad

2021-08-09 23:09 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  vx_reference *output;
Why don't we use GstTIOVXPad for the output as we do for the input?

2021-08-10 19:07 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  guint out_pool_size;
We aren't using TIOVXPad;s here, but in the next PR this will be moved to a MISO pad

2021-08-10 19:42 UTC, merged