Feature/add-the-crosscompilation-support
TexasInstruments/edgeai-gst-plugins pull request #4
Opened 2021-07-07 14:03 UTC by dchvs

2021-07-07 21:03 UTC, rrcarlosrodriguez requested changes

2021-07-07 21:15 UTC, rrcarlosrodriguez requested changes

2021-07-07 21:15 UTC, rrcarlosrodriguez commented on README.md
> +sed -i "s|cross_compiler=''|cross_compiler='$CROSS_COMPILE'|g" crosscompile.txt
I don't like the user doing this every time. We should find a way to do this automatically.

2021-07-08 20:28 UTC, michaelgruner requested changes

2021-07-08 20:28 UTC, michaelgruner commented on README.md
> +## Build the GstTIOVX with cross compilation
Cross compiling the project

2021-07-08 20:28 UTC, michaelgruner commented on README.md
> +meson build --prefix=/usr --cross-file crosscompile.txt
The idea of being able to specify which cross-compile file to use, is that eventually we have several files for different architectures. I recommend naming this file after the architecture (the prefix in the toolchain we use, i.e: aarch64-none-linux) and moving them to a `cross` directory.

2021-07-08 20:28 UTC, michaelgruner commented on crosscompile.txt
> +cross_compiler=''
Given that this will be specific to a platform, we can hardcode this to TI's toolchain.

2021-07-08 20:28 UTC, michaelgruner commented on crosscompile.txt
> +pkgconfig = '/usr/bin/pkg-config'
Don't force any specific binary on the user. Use plain `pkg-config`  or `/usr/bin/env pkg-config`

2021-07-08 20:28 UTC, michaelgruner commented on crosscompile.txt
> +libdir = 'lib/'
This is wrong I think. It should be `prefix + '/lib/`

2021-07-08 20:28 UTC, michaelgruner commented on meson.build
> +glib_dep      = dependency('glib-2.0',           version : glib_req)
I would expect that gstreamer already carries this as a dependency?

2021-07-08 22:30 UTC, michaelgruner requested changes

2021-07-08 22:30 UTC, michaelgruner commented on pkgconfig/tiovx.pc
> +includedir1=${prefix}/include/processor_sdk/tiovx/kernels_j7/include/
I like this, but I don't like the names. Let's use significative names, for example: `includedir_j7kernels`, `includedir_kernels`, `includedirs_utils`, etc...

2021-07-09 17:25 UTC, dchvs commented on README.md
> +sed -i "s|cross_compiler=''|cross_compiler='$CROSS_COMPILE'|g" crosscompile.txt
Thanks. I added an environment to set up all the cross compilation required variables.

2021-07-12 13:19 UTC, emmadrigal requested changes

2021-07-12 13:19 UTC, emmadrigal commented on README.md
> +chmod +x crossbuild/environment
Can't you push this file already with the +x?

Also, since you are sourcing it, do you need to be an executable?

2021-07-12 13:19 UTC, emmadrigal commented on README.md
> +ninja -j8
You don't need to force ninja to use multiple cores it will already attempt to use the max amount: https://ninja-build.org/manual.html#_running_ninja.

Leave it as `ninja`

2021-07-12 13:19 UTC, emmadrigal commented on README.md
> +ninja  -j8
See my comment above about multiple cores

2021-07-12 13:19 UTC, emmadrigal commented on README.md
> +## Compiling the project native
Typo `natively`

2021-07-12 13:19 UTC, emmadrigal commented on README.md
> +# Create an environment with the:
I don't think its clear what you mean by this...

Is this:
* sourcing the directories
* creating said directories
* something else?

2021-07-12 13:19 UTC, emmadrigal commented on crossbuild/DEBIAN/control
> +Maintainer: Daniel Chaves <daniel.chaves@ridgerun.com>
I'm not sure if you should be the maintainer, in other projects we have used the client's info.

Please ask this in our internal chat team.

2021-07-12 13:19 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovx.c
> +#include "app_color_convert_module.h"
Wrong include order: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

2021-07-12 13:19 UTC, emmadrigal commented on pkgconfig/vision_apps_modules.pc
> +Description: TI OVX API
Wrong name and description

2021-07-12 15:59 UTC, dchvs commented on README.md
> +chmod +x crossbuild/environment
Thanks, it's not necessary to make it executable; for some reason it just seemed to me. Change applied.

2021-07-12 17:40 UTC, m-herrera requested changes

2021-07-12 17:40 UTC, m-herrera commented on crossbuild/environment
> +cat > $BUILD_ROOT/crossbuild/aarch64.ini <<EOL
I think it's safer to surround variables with {} as well as ""
for example `cat > "${BUILD_ROOT}"/crossbuild/aarch64.ini <<EOL`

Same applies for all the variables in  this file

2021-07-12 17:46 UTC, emmadrigal approved these changes

2021-07-12 20:22 UTC, merged