Feature/mosi subclass initialization
TexasInstruments/edgeai-gst-plugins pull request #43
Opened 2021-08-10 19:42 UTC by emmadrigal

2021-08-10 22:54 UTC, michaelgruner requested changes

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +      g_value_set_int (value, pad->pool_size);
Always serialize these accesses.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +      pad->pool_size = g_value_get_int (value);
Always serialize these accesses.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    vxReleaseReference (self->exemplar);
Always null out what you just freed.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    gst_object_unref (self->buffer_pool);
Always null out what you just freed.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  tiovx_miso_pad->param_id = -1;
Param ID is unsigned. Just double checking this is still the desired behavior you want.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  vx_reference *exemplar;
Why is this a pointer to a pointer? I'm almost certain it's just `vx_reference exemplar`

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +gst_tiovx_miso_pad_set_params (GstTIOVXMisoPad * pad, vx_reference * exemplar,
remove the extra pointer in the exemplar.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +}
You may want to lock this.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +gboolean gst_tiovx_miso_negotiate (GstAggregator * self);
make these static. These are not indented correctly

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  GstVideoInfo info;
`GstVideoInfo info = GST_VIDEO_INFO_INIT`

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  vx_reference reference;
= NULL

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +      &reference, size, &tiovx_miso_pad->buffer_pool);
Why are you passing a double pointer? There is no need to do this, unless it's an output parameter, which I believe it's not.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    vxReleaseReference (&reference);
NULL out what you just freed.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    GstVideoInfo info;
GST_VIDEO_INFO_INIT

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    caps = gst_pad_get_current_caps (agg->srcpad);
Should we be using the caps that come with the query? Or at least considering them?

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    caps = gst_pad_get_current_caps (agg->srcpad);
leak

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  for (l = GST_ELEMENT (agg)->sinkpads; l; l = l->next) {
always use `g_list_next` instead of accessing the structure directly.

2021-08-10 22:54 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  for (l = GST_ELEMENT (self)->sinkpads; l; l = l->next) {
`g_list_next`

2021-08-10 22:54 UTC, michaelgruner commented on tests/check/libs/gsttiovxmiso.c
> +  tcase_add_test (tc, test_success);
Nice test! Hopefully we could test each virtual method fail.

2021-08-10 23:45 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  vx_reference *exemplar;
The exemplar is actually in the module, and we just keep a pointer to the exemplar.

This is the standard we have been following in both SISO and SIMO

2021-08-10 23:50 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  GstVideoInfo info;
`GST_VIDEO_INFO_INIT`  doesn't exit

2021-08-10 23:50 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +      &reference, size, &tiovx_miso_pad->buffer_pool);
It is an output parameter

2021-08-10 23:51 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +      &reference, size, &tiovx_miso_pad->buffer_pool);
This is meant so that we can keep a reference to the pool for future reconfiguration

2021-08-11 00:04 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +gst_tiovx_miso_pad_set_params (GstTIOVXMisoPad * pad, vx_reference * exemplar,
We are handling pointers to the reference in the subclass module in all of our classes

2021-08-13 15:26 UTC, rrcarlosrodriguez requested changes

2021-08-13 15:26 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.h
> +gst_tiovx_configure_pool (GstDebugCategory * category, GstBufferPool * pool, vx_reference * exemplar, GstCaps * caps, gsize size, guint num_buffers);
Document this public method and indent

2021-08-13 15:26 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.h
> +  gboolean      (*configure_module)         (GstTIOVXMiso *agg);
This one is not documented above

2021-08-13 15:26 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.h
> +  GstCaps *     (*fixate_caps)              (GstTIOVXMiso *self, GList * sink_caps_list, GstCaps *src_caps);
This one is not documented above

2021-08-13 15:26 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.h
> + * @param_id: Parameter id that will be used to enqueue this parameter to the Vx Graph
Document a description of the function and the return value

2021-08-16 15:05 UTC, jafet-chaves approved these changes

2021-08-16 16:22 UTC, rrcarlosrodriguez approved these changes

2021-08-16 18:05 UTC, merged