Feature/implement buffer pool
TexasInstruments/edgeai-gst-plugins pull request #5
Opened 2021-07-07 20:03 UTC by emmadrigal

2021-07-09 16:50 UTC, michaelgruner requested changes

2021-07-09 16:50 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +      vxCreateObjectArray (vxGetContext (self->reference), self->reference,
Attack this the other way around:
1. Let GstVideoBufferPool use our allocator
2. The GstVideoBufferPool will consider alignment, padding, etc..., allocate and add a VideoMeta
3. You take the video meta, and use that info to create the exemplar.

2021-07-09 16:50 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmeta.h
> +struct _GstTIOVXMeta {
I would prefer to keep this encapsulated. This is, keep it in the source and add public accessors.

2021-07-12 14:31 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +gst_tiovx_buffer_pool_new (const vx_reference reference)
We might be able to do that. However, I think using an external one is better, since the `examplar` comes from one of TI's modules, and doing it this way we ensure that it matches 1:1 with the one used by the processing graph.

2021-07-13 14:15 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  status =
the examplar already calculates the plane sizes, if another value the import fails.

2021-07-13 15:35 UTC, rrcarlosrodriguez requested changes
Minor changes requested

2021-07-13 15:35 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.h
> +GstTIOVXBufferPool *gst_tiovx_buffer_pool_new(const vx_reference examplar);
exemplar

2021-07-13 15:35 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +#define TIOVX_ARRAY_LENGHT 1
Length

2021-07-13 15:35 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  vx_reference examplar;
exemplar

2021-07-13 15:35 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  ref = (vx_image) vxGetObjectArrayItem (tiovxmeta->array, 0);
Should we free this reference with  vxReleaseReference() ?

2021-07-13 15:56 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  ref = (vx_image) vxGetObjectArrayItem (tiovxmeta->array, 0);
Yes, thanks for the note

2021-07-13 23:18 UTC, michaelgruner requested changes

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  if (NULL == caps) {
This is what has me doubting. We are no longer using any of this.

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  if (!gst_video_info_from_caps (&self->caps_info, caps)) {
Again, we are not using this anywhere. I wonder if we should simply ignore them or, better yet, use the exemplar to validate that they match.

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +gst_tiovx_buffer_pool_new (const vx_reference exemplar)
do you think having a `gst_buffer_pool_config_set_examplar` is more inline with the GStreamer pattern? Like for example: `gst_buffer_pool_config_set_params`, [gst_buffer_pool_config_set_alignment](https://gstreamer.freedesktop.org/documentation/video/gstvideopool.html?gi-language=c#gst_buffer_pool_config_set_video_alignment), etc... What do you think?

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +
Here we need to check if the ultimately used allocator is tiovx. User could have replaced ours. (if it is tiovx we want to use theirs, it could be a specialized version).

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  status = vxQueryImage ((vx_image) self->exemplar, VX_IMAGE_SIZE, &img_size,
What are we using this for?

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  ret = GST_BUFFER_POOL_CLASS (gst_tiovx_buffer_pool_parent_class)->alloc_buffer(pool, &outbuf, params);
how are you sure this size matches the one of the exemplar? All this GStreamer/OVX handling of stuff separately makes me nervous. I think we should get rid of these loose ends.

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  gst_buffer_add_video_meta (outbuf,
Please use [gst_buffer_add_video_meta_full](https://gstreamer.freedesktop.org/documentation/video/gstvideometa.html?gi-language=c#gst_buffer_add_video_meta_full) so we can specify the plane locations to match exactly the ones in the VxImage. Otherwise Gst may compute the offset which may not match.

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  tiovxmeta->array =
Similar to `gst_buffer_add_video_meta` I recommend adding this logic to the meta. Something like `gst_buffer_add_tiovx_meta`

2021-07-13 23:18 UTC, michaelgruner commented on gst-libs/gst/tiovx/meson.build
> +  'gsttiovxmeta.h',
buffer pool?

2021-07-14 13:10 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxallocator.c
> +gst_tiovx_memory_get_data(GstMemory *memory) {
We would still need the memory to extract the ti_memory

2021-07-14 20:55 UTC, michaelgruner approved these changes
Approved with changes, please consider them before merging.

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +void gst_buffer_pool_config_set_exemplar(GstStructure * config, const vx_reference exemplar) {
Why is the indenter not working?

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  GstVideoBufferPool base;
Do we want to inherit directly from GstBufferPool?

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +
Collapse newlines

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +
pointer guards

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  vxReleaseReference (&self->exemplar);
Please check the exemplar actually exists before attempting to free it.

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  GST_INFO_OBJECT (self, "New TIOVX buffer pool");
Initialize pool members

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxbufferpool.c
> +  vxQueryImage ((vx_image) self->exemplar, VX_IMAGE_SIZE, &img_size,
Please check the exemplar exists before proceeding.

2021-07-14 20:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxmeta.c
> +static const vx_size k_TIOVX_array_lenght = 1;
I feel like this naming breaks our standard.

2021-07-14 21:17 UTC, merged