Feature/miso process graph
TexasInstruments/edgeai-gst-plugins pull request #54
Opened 2021-08-16 18:06 UTC by emmadrigal

2021-08-18 15:36 UTC, rrcarlosrodriguez requested changes

2021-08-18 15:36 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  meta = (GstTIOVXMeta *) gst_buffer_get_meta (buffer, GST_TIOVX_META_API_TYPE);
Use utils function to avoid parsing the meta in the class

2021-08-18 15:36 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +#include "gsttiovxmeta.h"
This shouldn't be needed here

2021-08-18 15:36 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  GstTIOVXBufferPool *buffer_pool;
Why TIOVXBufferPool? Let's use GstBufferPool because the pool could be TensorBufferPool as well

2021-08-18 15:36 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxutils.c
> +    if (GST_TIOVX_IS_BUFFER_POOL ((buffer)->pool)) {
Please put a comment here: `TODO: Add Tensor Buffer Pool support`

2021-08-18 16:51 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    GST_TIOVX_MISO_PAD (agg->srcpad)->buffer_pool =
Why this indentation looks odd?

2021-08-20 17:02 UTC, rrcarlosrodriguez requested changes

2021-08-20 17:02 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    gst_aggregator_pad_drop_buffer (pad);
Why dropping the buffer?

2021-08-20 17:02 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +
Remove empy line and pointer guards

2021-08-20 17:02 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (event != NULL)
Why this? I would expect the event to be always non NULL. Anyway, you should check if event is NULL at the beggining of the function, and do ret = GST_AGGREGATOR_CLASS (...

2021-08-20 18:00 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  /* Ensure valid graph + references */
You are right, it is lost, this verification is done during the module initialization

2021-08-20 18:04 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    GST_ERROR_OBJECT (self, "In buffer: %" GST_PTR_FORMAT, in_buffer);
This is dirty code from a debugging I was performing

2021-08-20 18:06 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +    gst_aggregator_pad_drop_buffer (pad);
Dropping the buffer actually frees the reference from the sinkpads: https://gstreamer.freedesktop.org/documentation/base/gstaggregator.html?gi-language=c#gst_aggregator_pad_drop_buffer 
This marks it as done for further processing

2021-08-20 18:07 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +
`negotiated_src_caps` is a gstreamer function, the standard is not to perform pointer guard checking

2021-08-20 18:10 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxmiso.c
> +  if (event != NULL)
You are right, I based this on the `VideoAggregator` which on some cases made `event = NULL`

2021-08-20 21:35 UTC, merged