Feature/implement colorblend structure
TexasInstruments/edgeai-gst-plugins pull request #58
Opened 2021-08-18 22:49 UTC by m-herrera

2021-08-18 22:57 UTC, rrcarlosrodriguez requested changes

2021-08-18 22:57 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovx.c
> +#include "gsttiovxdlcolorblend.h"
Alphabetical order

2021-08-18 22:57 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovx.c
> +  ret = gst_element_register (plugin, "tiovxdlcolorblend", GST_RANK_NONE,
Check if register fail and put and error message

2021-08-18 22:57 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxdlcolorblend.c
> +/* TODO Update element description*/
Remove this comment

2021-08-18 22:57 UTC, rrcarlosrodriguez commented on ext/tiovx/gsttiovxdlcolorblend.h
> +G_DECLARE_FINAL_TYPE(GstTIOVXDLColorBlend, gst_tiovx_dl_color_blend, GST_TIOVX,
This declaration is not similar to the one used in multiscaler and colorconvert, why?

2021-08-18 23:03 UTC, emmadrigal requested changes

2021-08-18 23:03 UTC, emmadrigal commented on ext/tiovx/gsttiovxdlcolorblend.c
> +#define TIOVX_DL_COLOR_BLEND_SUPPORTED_FORMATS_SINK "ANY"
Is this correct?

2021-08-18 23:03 UTC, emmadrigal commented on ext/tiovx/meson.build
> +  'gsttiovxdlcolorblend.h'
Alphabetical order

2021-08-19 00:52 UTC, m-herrera commented on ext/tiovx/gsttiovxdlcolorblend.c
> +#define TIOVX_DL_COLOR_BLEND_SUPPORTED_FORMATS_SINK "ANY"
It is not, but we don't have the supported formats yet, I will update them as soon as they are defined

2021-08-24 15:04 UTC, emmadrigal commented on ext/tiovx/gsttiovxdlcolorblend.c
> +#define TIOVX_DL_COLOR_BLEND_SUPPORTED_FORMATS_SINK "ANY"
ok

2021-08-30 22:08 UTC, merged