Feature/friendlier cross compilation
TexasInstruments/edgeai-gst-plugins pull request #6
Opened 2021-07-15 05:31 UTC by michaelgruner

2021-07-19 17:08 UTC, dchvs requested changes

2021-07-19 19:05 UTC, michaelgruner commented on crossbuild/environment
> +CROSS_CC=`find $PSDKR_PATH -name "${HOST_TRIPLET}-gcc" -exec sh -c "{} --version >/dev/null 2>&1" \;  -print`
As per now the path is known, but I'm thinking in the time the toolchain is upgraded, I'm trying to avoid hardcoding a specific name/version.

2021-07-19 19:23 UTC, michaelgruner commented on crossbuild/environment
> +SOURCE_ROOT=`realpath $(dirname $0)/..`
This hardcodes a path to the source root. So no matter from where you end up calling the build, it will be valid.

2021-07-20 16:52 UTC, dchvs commented on crossbuild/environment
> +CROSS_CC=`find $PSDKR_PATH -name "${HOST_TRIPLET}-gcc" -exec sh -c "{} --version >/dev/null 2>&1" \;  -print`
The Toolchain it's installed / needed to be installed at the PSDKR root dir. So, you can do a level 1 find to the Toolchain dir where you want to get the compiler binary from...

Pass this output to the search:

`find -maxdepth 1 | grep  "^./gcc-"`

2021-07-20 16:53 UTC, dchvs commented on crossbuild/environment
> +SOURCE_ROOT=`realpath $(dirname $0)/..`
Ok, great

2021-07-21 15:14 UTC, dchvs approved these changes

2021-07-21 18:53 UTC, merged