Feature/add gsttiovxsiso class
TexasInstruments/edgeai-gst-plugins pull request #7
Opened 2021-07-15 20:26 UTC by rrcarlosrodriguez

2021-07-15 21:43 UTC, emmadrigal approved these changes

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +#include <TI/j7.h>
Wrong include order, should be:
```
siso.h

ti/gst includes

the rest of our includes
```

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  vx_reference out_image;
I think `vx_object_array` and `vx_reference` can be initialized to `NULL` and `vx_size` to `0`

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  vx_node node;
I think all of these can be initialized to `NULL

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  /* Create OpenVx Context */
The correct spelling is `OpenVX`

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  uint32_t in_refs, out_refs;
Initialize these variables

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  vx_size dest_num_planes;
Initialize these variables

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  gsize size;
Initialize to 0

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  void *addr[MAX_NUMBER_OF_PLANES];
This can be initialized by:
```
...OF_PLANES] = {NULL};
```

2021-07-15 21:43 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  uint32_t bufsize[MAX_NUMBER_OF_PLANES];
This can be initialized by:
```
OF_PLANES] = {0};
```

2021-07-19 22:52 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (VX_SUCCESS != status) {
Parameter has to be released here too

2021-07-19 23:18 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    goto error;
deinit_module should be called here.

2021-07-20 16:42 UTC, michaelgruner requested changes

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  priv->out_pool = NULL;
Initializa all members of the private.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  status = gst_ti_ovx_siso_graph_processing (self);
All your other methods are named after a verb, try to follow that pattern.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  }
why are you removing all pools? the idea is to use the pool we are being offered, if it is a TIOVX one.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    vx_reference * handler, guint pool_size)
I don't like how this method is defined:
1. the `params_list` list is defined using[] while `handler` list is defined using `**`
2. `handler` is a terrible name for a list. And, if it's not supposed to be a list, why are we passing a double pointer (vx_reference is already a pointer underneath)
3. This is a generic method for parameters, but by naming the last parameter `pool_size` you are assuming its for buffers. Either rename the method or make it completely generic.
4. `ref_list` and `ref_list_size` are much better names.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  g_return_val_if_fail (pool_size >= MIN_POOL_SIZE, VX_FAILURE);
Again, is this method only for pools? if so, orient all the names as such.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  node = *priv->node;
I don't understand why we need to pass a list and always take the first element. Just pass the node.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  }
repeated?

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    GST_ERROR_OBJECT (self, "Graph creation failed");
Always include the return code in the message.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  priv->init_completed = TRUE;
I don't like having a separate flag. We have plenty of variables we can use (graph, for example). This just adds potential coherence problems.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    goto free_graph;
This single-input/single-output pattern is wrong. Please revisit and fix.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +gst_ti_ovx_siso_graph_processing (GstTIOVXSiso * self)
Follow your naming standard.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +add_graph_parameter_by_node_index (GstTIOVXSiso * self,
If your first argument is `self`, then this is a method of your class and should follow the method naming standard.

2021-07-20 16:42 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.h
> +#define NUM_PARAMETERS         2
Private

2021-07-20 16:42 UTC, michaelgruner commented on meson.build
> +glib_dep      = dependency('glib-2.0',           version : glib_req)
Not needed. Please remove. Just adding maintenance burden to ourselves.

2021-07-21 19:50 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    goto free_graph;
Why? this goto is intended to free the graph created previously

2021-07-21 21:59 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxsiso.h
> +#define NUM_PARAMETERS         2
What do you mean? These are used by the colorconvert, that is why we put them here

2021-07-22 01:00 UTC, michaelgruner requested changes

2021-07-22 01:00 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  }
if this fails this shouldn't be in the init.

2021-07-22 01:00 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (VX_SUCCESS != vxGetStatus ((vx_reference) priv->graph)) {
Will `vxGetStatus` fail if given a NULL graph? If so, we shouldn't be doing this.

2021-07-22 01:00 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  }
Do we really need references to the pools? If not, remove.

2021-07-22 01:00 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +      pool_needed = FALSE;
Where are you saving the pool? if there is no need to save then this leaves a leak.

2021-07-22 01:00 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    goto free_graph;
ah, sorry. The virtual_method name is confusing. I thought this method created the graph.

2021-07-22 01:00 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (!gst_tiovx_siso_modules_deinit (self)) {
I recommend not calling this here. This will free resources that weren't properly allocated here. The graph, for example. Maintain symmetry and deallocate only what you've allocated here.

2021-07-22 01:30 UTC, rrcarlosrodriguez commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (VX_SUCCESS != vxGetStatus ((vx_reference) priv->graph)) {
That is the idea, the idea is to verify if the graph was created, if not, avoid running the modules_deinit

2021-07-22 22:22 UTC, michaelgruner requested changes

2021-07-22 22:22 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  }
to be tackled in a new PR

2021-07-22 22:22 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (VX_SUCCESS != vxGetStatus ((vx_reference) priv->graph)) {
I mean, if `vxGetStatus` will segfault if we pass in a null graph. But according to our conversation it won't.

2021-07-22 22:22 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  }
Don't this. the passthrough may change spontaneously.

2021-07-22 22:22 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +  if (!gst_tiovx_siso_modules_deinit (self)) {
ping.

2021-07-22 22:48 UTC, merged