WIP: Feature/implement colorblend element
TexasInstruments/edgeai-gst-plugins pull request #70
Opened 2021-08-30 23:50 UTC by m-herrera

2021-08-31 16:55 UTC, michaelgruner requested changes

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  }
I don't like this very much. Can we save a reference to the video pad when it is created?

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +      colorblend->tensor_input.graph_parameter_index = i;
I don't see `i` ever increasing.

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +    }
Why are we doing this again?

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  }
Is `0` not a valid target?

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  *node = self->obj->node;
Let's stop iterating through all the pads every time. We need to save a reference to each pad and use that.

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +    goto out;
De we not want to release everything else if this fails?

2021-08-31 16:55 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  }
what is going on here? this is not fixating anything.

2021-09-02 17:56 UTC, m-herrera commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  }
Yes, but this variable is a gchar containing the nickname not the id

2021-09-03 00:19 UTC, michaelgruner requested changes

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  g_return_val_if_fail (image_input_found, FALSE);
These macros should be used for programming errors. This is not a programming error, this is a runtime error.

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  for (l = sink_pads_list; l != NULL; l = g_list_next (l)) {
Why did we change the "save a reference" approach. It's way cleaner than doing this. This seems unnecessary.

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +        goto out;
This is not using the single-input/single-output pattern appropriately.

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +    g_return_val_if_reached (FALSE);
Is this a programming error? if not, please change the use of this macro

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  for (l = sink_pads_list; l; l = l->next) {
To me it makes no sense to iterate everywhere looking for the pads. I would save a reference at creation time.

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +          (vx_reference *) & self->obj->tensor_input.tensor_handle[0],
Unless this is an output parameter and we are allocating the tensor inside this method, we should not pass a double pointer. We must stop doing this, this can lead to serious problems and unnecessary indirections.

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +  for (l = sink_caps_list; l != NULL; l = g_list_next (l)) {
Again, save a reference at creation time and we wouldn't need to iterate every time.

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +    gst_caps_unref (caps);
Are you sure you should be releasing this caps?

2021-09-03 00:19 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +    gst_caps_unref (caps);
Aren't we freeing this caps two times?

2021-09-03 16:42 UTC, michaelgruner approved these changes

2021-09-03 16:42 UTC, michaelgruner commented on ext/tiovx/gsttiovxdlcolorblend.c
> +    goto out;
This is not a good usage of the single-input/single-output pattern.

2021-09-03 23:22 UTC, merged