Feature/mosaic implementation
TexasInstruments/edgeai-gst-plugins pull request #76
Opened 2021-09-02 15:39 UTC by emmadrigal

2021-09-02 16:23 UTC, jafet-chaves requested changes

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  GList *l = NULL;
I recommend changing this to a more significant name. "next" perhaps?

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  vx_object_array input_arr_user[] =
This is strange, should not this be enough (all the rest of elements would be implicitly NULL)?:
`  vx_object_array input_arr_user[] =   { NULL };`

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  GList *l = NULL;
Again I suggest a more significant name for this variable. Check in other places for this pattern.

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  caps = gst_pad_get_current_caps (src_pad);
Why this check is needed?

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +    caps = gst_pad_get_current_caps (sink_pad);
Why this check is needed?

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  gst_child_proxy_child_added (GST_CHILD_PROXY (element), G_OBJECT (newpad),
This can be in the parent class. Take a look at SIMO.

2021-09-02 16:23 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmosaic.c
> +  gst_child_proxy_child_removed (GST_CHILD_PROXY (mosaic), G_OBJECT (pad),
This can be in the parent class. Take a look at SIMO.

2021-09-02 17:09 UTC, emmadrigal commented on ext/tiovx/meson.build
>    'gsttiovxdlpreproc.h',
This is already in alphabetical order

2021-09-02 17:11 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +     struct _GstTIOVXMosaicPad
That isn't necesarry since the mosaicpad will only be used in the mosaic. This is the way that it is done in GSTreamer elements such as the compositor.

2021-09-02 17:12 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  vx_object_array input_arr_user[] =
The array size has to match the number of elements. in this case we need at least 8 NULL values

2021-09-02 17:12 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  caps = gst_pad_get_current_caps (src_pad);
non-video caps for example have no video info. This is the standard way to check for success in getting the value, and we avoid configuring the element with invalid values

2021-09-02 17:13 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    caps = gst_pad_get_current_caps (sink_pad);
non-video caps for example have no video info. This is the standard way to check for success in getting the value, and we avoid configuring the element with invalid values

2021-09-02 17:58 UTC, jafet-chaves approved these changes

2021-09-03 01:39 UTC, michaelgruner requested changes

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +    GST_ERROR_OBJECT (self, "%d\t%u\t%d\t%s", input_value, *output_value,
I 't don't think this error says anything. Was it for debug purposes?

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +      gst_caps_unref (caps);
This is not a correct use of the single-input/single-output pattern.

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  /* Number of time to clear the output buffer before it gets reused */
`times

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  GstTIOVXMosaic *self = NULL;
Leave some spaces to improve readability.

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  GstStructure *s;
Initialize.

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  g_return_val_if_fail (self, output_caps);
leave some spaces to improve readability.

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  for (l = GST_ELEMENT (self)->sinkpads; l; l = l->next) {
use `l->next` instead of `l = g_list_next (l)`

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +    if (!GST_TIOVX_IS_MOSAIC_PAD (sink_pad)) {
Why would this happen?

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +    gdouble cur_fps;
Initialize

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +      goto out;
leak. use the single-input/ single-output pattern.

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +    }
What is going on here? can we even have different framerates? shouldn't we be forcing equal frame rates everywhere?

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  }
Why 25?

2021-09-03 01:39 UTC, michaelgruner commented on ext/tiovx/gsttiovxmosaic.c
> +  output_caps = gst_caps_fixate (output_caps);
Where are you considering the src caps? what if they are not compatible? you need to intersect the required caps with the current src caps.

2021-09-03 14:15 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +static const int k_window_downscaling_max_ratio = 4;
I'll add an issue to address for all variables

2021-09-03 14:18 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    GST_ERROR_OBJECT (self, "%d\t%u\t%d\t%s", input_value, *output_value,
Yes it was for debugging

2021-09-03 14:24 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    if (!GST_TIOVX_IS_MOSAIC_PAD (sink_pad)) {
This is from an partial implementation fo the `background` pad

2021-09-03 15:17 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +    }
This logic is following gstpluginsbase compositor

2021-09-03 15:17 UTC, emmadrigal commented on ext/tiovx/gsttiovxmosaic.c
> +  }
This logic is following gstpluginsbase compositor

2021-09-03 16:46 UTC, michaelgruner approved these changes

2021-09-03 17:23 UTC, merged