Empty exemplars to avoid double mem free
TexasInstruments/edgeai-gst-plugins pull request #77
Opened 2021-09-02 23:57 UTC by rrcarlosrodriguez

2021-09-02 23:57 UTC, rrcarlosrodriguez commented
This PR fixes issue #75

2021-09-03 00:06 UTC, jafet-chaves approved these changes

2021-09-03 00:12 UTC, emmadrigal approved these changes

2021-09-03 00:25 UTC, michaelgruner requested changes

2021-09-03 00:25 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsiso.c
> +    }
I believe you're trying to remove a non-existing pool.

2021-09-03 00:25 UTC, merged