Feature/add gsttiovxsimo class
TexasInstruments/edgeai-gst-plugins pull request #8
Opened 2021-07-15 21:17 UTC by jafet-chaves

2021-07-15 22:11 UTC, emmadrigal requested changes

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  GstTIOVXSimo *self;
Init to `NULL`

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      GstCaps *filter;
Init to `NULL`

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  gpointer pool_size;
Init to NULL

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  params_list = malloc (priv->num_pads * sizeof (*params_list));
Use `g_malloc0` and release with `g_free`

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  GstTIOVXSimo *self;
init to `NULL`

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      GstCaps *caps;
Init to null

2021-07-15 22:11 UTC, emmadrigal commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      /* TODO: call fixate_caps virtual method first */
Why is there a `TODO` here?

2021-07-15 23:03 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    return status;
Please, use the `goto label `statements.

2021-07-15 23:12 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +gst_tiovx_simo_finalize (GObject * object)
`gobject`, might be a more significant variable.

2021-07-15 23:14 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    default:
Should we return `GST_STATE_CHANGE_FAILURE` here?

2021-07-15 23:28 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  for (parameter_index = 1; parameter_index < priv->num_pads; parameter_index++) {
Please consider using the regular counter `i`, as it increases the code readability.

2021-07-15 23:39 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +gst_tiovx_simo_set_caps (GstTIOVXSimo * self, GstPad * pad, GstCaps * incaps)
This function is too big, please factorize it.

2021-07-15 23:41 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (!gst_video_info_from_caps (&in_info, incaps))
You might want to use `g_assertions` here.

2021-07-15 23:53 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  goto exit;
Follow the single-input/single-output pattern, that is, a natural sequence of the code until reaching out the return. So, the first "goto label" you step with from top to bottom, should be the last one to be declare and therefore sequeantilly freed.

2021-07-15 23:56 UTC, dchvs commented on gst-libs/gst/tiovx/gsttiovxsimo.h
> +#include <gst/base/base-prelude.h>
Alphabetical order.

2021-07-16 00:03 UTC, dchvs requested changes
@jafet-chaves , changes requested

2021-07-16 14:51 UTC, jafet-chaves commented on meson.build
> +gst_video_dep = dependency('gstreamer-video-1.0',version : gst_req)
Yes, this is needed but I see its duplicated. I'll remove it.

2021-07-16 15:36 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      /* TODO: call fixate_caps virtual method first */
This is due to it was agreed this PR won't contain the implementation for this part.

2021-07-16 15:51 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (GST_IS_TIOVX_SIMO (self), FALSE);
GST_IS_TIOVX_SIMO already does it

2021-07-16 17:07 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    default:
No, I don't believe so this is required. That would mean the code fails for any other state transition.

2021-07-19 21:55 UTC, michaelgruner requested changes

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    vx_reference * handler, guint pool_size)
is `handler` a list of size `pool_size`? If so, it is not a very good name. Use a name that hints the reader that `handler` is, in fact,  a list of `pool_size`. Maybe `ref_list` and `ref_list_size` or something like that.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (pool_size >= MIN_POOL_SIZE, VX_FAILURE);
The problem I have with this is that this method seems generic (for any parameter), but here you are assuming that the parameter will be buffers.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  node = *priv->node;
This is another point that is confusing to me. If this is a list of nodes, why do we always assume that the parameter will be written to the first element in the list.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    GST_ERROR_OBJECT (self, "Add parameter to graph failed");
We need to free the parameter if this failed.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    GST_ERROR_OBJECT (self, "Add parameter to graph failed");
Also, always put the status code of the failure.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  GST_DEBUG ("gst_ti_ovx_simo_modules_init");
_OBJECT

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +gst_tiovx_simo_modules_null_to_ready_init (GstTIOVXSimo * self)
start and stop are the common names for these methods. `gst_tiovx_simo_start` and `gst_tiovx_simo_stop`

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  priv->srcpads = g_hash_table_new (NULL, NULL);
Wait, above you are asking for the number of pads, but here you are creating the hash table for the pads? this doesn't seem right. were are you storing the pads? pads are going to be created mostly in the null state, so by now we are already late.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (0 != appCommonInit ()) {
Dont use the numeric value. Use the enum name.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    goto free_context;
We need to call deinit_module here.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    goto free_graph;
This single-input/single-output pattern is not okay. At this point you still don't have a graph. Please revise the full thing.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  gpointer pool_size = NULL;
Why is this a gpointer?

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +          g_hash_table_lookup (priv->out_pool_sizes, GUINT_TO_POINTER (i));
Please use GPOINTER_TO_GUINT and make pool_size an integer.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        priv->output[i], *(guint *) (pool_size));
using pool_size as this is incorrect.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_free (params_list);
is there a max number of potential parameters? if so, I would very much recommend using static memoryof dynamic allocation.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  priv->module_init = TRUE;
Do we really need another flag? can we use the graph or something like that?

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  vxReleaseGraph (&priv->graph);
Always null out freed variables.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  GST_DEBUG ("gst_ti_ovx_simo_modules_deinit");
_OBJECT

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_hash_table_unref (priv->out_pool_sizes);
This is not the place for this. You created the hash table on the start method, free it on the stop method.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  /* Handle case in which transition from READY to NULL did not occurred */
This is not necessary if allocation/deallocation is done symmetrically.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    case GST_STATE_CHANGE_READY_TO_NULL:
This is not the correct way to do this. You need to chain to the parent method. Please refer to the an example in the mainstream repos.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  free (params_list);
g_free

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  return NULL;
Why are you returning NULL?

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    if (g_hash_table_contains (priv->srcpads, GUINT_TO_POINTER (index))) {
Are we testing this? how does this pass? you create the hash table after we start transition states, this should definitely fail.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  sink_caps = gst_pad_get_pad_template_caps (sink_pad);
You don't need this, the template is already considered.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +gst_tiovx_simo_default_get_caps (GstTIOVXSimo * self, GstPad * sink_pad,
You don t need to pass in the pad

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        gst_caps_intersect_full (src_caps, filter_sink_intersect,
What is going on here? src_caps are always null....

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    GList *next = src_caps_sublist->next;
always use g_list_next instead

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    g_list_find (src_caps_sublist, (GstCaps *) filtered_sink_src_intersect);
No this is incorrect. Just intersect all caps in the incoming list. no need for anything fancier than that.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      gst_structure_remove_fields (caps_struct, "width", "height", NULL);
Why are you doing this? the default is to intersect. This is a task for the multiscaler.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    GstCaps * filter, GList * src_caps_list)
Where are you using the filter?

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      GstCaps *filter = NULL;
Please move to a separate method.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        GList *next = src_pads_sublist->next;
Use g_list_next always.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        g_list_find (src_pads_sublist, (GstPad *) src_pad);
This is not doing anything....

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +            gst_pad_get_pad_template_caps (src_pad), -1);
No, you need to send a caps query to the pad.

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  return ret;
Where are you returning the output caps? The method should return the output caps

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      gst_query_set_caps_result (query, g_list_nth_data (src_caps_list, 0));
No, you should be adding here the caps returned by get caps...

2021-07-19 21:55 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  GST_DEBUG_OBJECT (pad, "have new caps %p %" GST_PTR_FORMAT, sink_caps,
What is going on here?

2021-07-19 22:16 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    vx_reference * handler, guint pool_size)
No, handler is not supposed to be a list, instead is just an item from priv->output_refs. In any I agree handler is not a good name, perhaps "reference"?

2021-07-19 23:13 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (0 != appCommonInit ()) {
What do you mean? appCommonInit is not part of the OpenVX API.

2021-07-20 00:14 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_free (params_list);
Yes, but it really depends of the OpenVX node instantiated in the subclass which the base class is not aware of beforehand.

2021-07-20 16:43 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_return_val_if_fail (pool_size >= MIN_POOL_SIZE, VX_FAILURE);
Do you suggest to check pool_size >= MIN_POOL_SIZE outside this function, then?

2021-07-20 16:46 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  node = *priv->node;
I don't think it ever would be a case where priv->node is set to a list of vx_nodes in the first?

2021-07-20 16:53 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  priv->module_init = TRUE;
I think module_init works fine, there are other issues that have to be considered in using the graph. For example, the graph can be NULL and init_module have been called already (thus requiring to call deinit_module)

2021-07-21 00:43 UTC, michaelgruner requested changes

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        "Add parameter to graph failed, vx_status %" G_GINT32_FORMAT,
Normally, the explicit `G_GINT32_FORMAT` is only needed for 64 bits, because it is not portable to smaller 32bit platforms. In this case, `%d` is enough

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        (int) status);
I suggest you accustom to avoid casts unless explicitly needed. Specially in C, casts have supper powers and you can change anything into anything, which may be very dangerous. Try to remove all casts except for the ones that have a special reason to be there.

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      (vx_reference *) image_reference_list;
Remove unnecessary cast

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (0 != appCommonInit ()) {
I mean, does appCommonInit return 0 or something like VX_SUCCESS? if it has a named constant, use that.

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    GST_ERROR_OBJECT (self, "Subclass did not implement deinit_module method");
This walks straight into a segfault

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_hash_table_remove_all (priv->srcpads);
Do we need to unref the pads?

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  gst_element_add_pad (GST_ELEMENT_CAST (self), srcpad);
I believe we need to activate the pad

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_hash_table_remove (priv->srcpads, GUINT_TO_POINTER (index));
How does this compile? Where is index declared?

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    src_pad = (GstPad *) g_list_nth_data (src_pads_sublist, i);
Use `GST_PAD()` safe cast. Remember the O(n) vs O(n^2) trick.

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    src_caps = (GstCaps *) src_caps_list->data;
This is a very nasty bug. This should be sublist. Otherwise you'll get the same caps every time.

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +      GstCaps *filter;
ping

2021-07-21 00:43 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +        GST_ERROR_OBJECT (self, "Get caps method failed");
leak. Apply single-input/single-output

2021-07-21 00:58 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +#include <stdio.h>
To import sscanf in `gst_tiovx_simo_request_new_pad`

2021-07-21 01:34 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  g_hash_table_remove_all (priv->srcpads);
No if I create the hash table with `g_hash_table_new_full` and provide g_object_unref as the `value_destroy_func`: https://developer.gnome.org/glib/stable/glib-Hash-Tables.html#g-hash-table-new-full.

2021-07-21 19:12 UTC, michaelgruner requested changes

2021-07-21 19:12 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  priv->module_init = TRUE;
This is misplaced here. If something goes wrong on the remainder of the function, this will remain TRUE, which will break the de-initialization.  I suggest dropping the extra flag and just use `priv->graph` as a initialization control flag.

2021-07-21 19:12 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  name = g_strdup_printf ("src_%u", priv->num_pads);
1. This will break the case where the user passes in a named pad (such as `src_0` instead of `src_%d`).
2. Using num_pads to name the pad is wrong. Imagine the following scenario:

```
                                   : num_pads = 0
request_pad (src_0) : num_pads = 1
request_pad (src_1) : num_pads = 2
 remove_pad (src_0): num_pads = 1
request_pad (src_1) <----- ERROR
```
remove_pad (src_0)

2021-07-21 19:12 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  gst_element_remove_pad (GST_ELEMENT_CAST (self), pad);
I'm unsure if you can call this with the LOCK held. Consider this if you get a deadlock during tests.

2021-07-21 19:12 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  srcpad = gst_pad_new_from_template (templ, name);
Check if this returns a valid pad. In case of error, srcpad will be null.

2021-07-21 19:12 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    g_return_val_if_fail (peer_caps, NULL);
Be careful of mixing runtime errors with programming errors. `g_return_val_if_fail` is for programming errors. I believe this is okay, but be mindful about the difference.

2021-07-21 19:12 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +    ret = gst_caps_intersect_full (ret, src_caps, GST_CAPS_INTERSECT_FIRST);
This produces a leak in `ret`. By overwriting the `ret` the last reference is lost. always unref the original `ret` after the intersection.

2021-07-22 21:01 UTC, michaelgruner requested changes

2021-07-22 21:01 UTC, michaelgruner commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  }
This logic is not okay. This is way more complicated than needed. Consider:
```
If name is src_%d:
 - Walk through pads and get highest index
 - Increase index by 1
 - Use the increased index
if name is src_N (for an integer N):
 - Walk through pads and search if N exists
 - if not, create the pad
```

2021-07-22 22:10 UTC, jafet-chaves commented on gst-libs/gst/tiovx/gsttiovxsimo.c
> +  if (VX_SUCCESS != vxGetStatus ((vx_reference) priv->graph)) {
vxGetStatus fails if graph is NULL

2021-07-23 15:02 UTC, emmadrigal requested changes

2021-07-23 16:08 UTC, emmadrigal approved these changes

2021-07-24 06:46 UTC, merged