Feature/add multiscaler element
TexasInstruments/edgeai-gst-plugins pull request #9
Opened 2021-07-16 20:04 UTC by dchvs

2021-07-19 20:05 UTC, michaelgruner requested changes

2021-07-19 20:05 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.h
> +#endif
Do we need this to be public? if not, move to the source.

2021-07-19 20:05 UTC, michaelgruner commented on tests/check/gsttiovxmultiscaler.c
> +GST_START_TEST (test_init_module)
I don't understand this test very much. What are we testing?

2021-07-19 20:34 UTC, jafet-chaves commented on ext/tiovx/gsttiovxmultiscaler.c
> +    multiscaler->output[i].width = (vx_int32) GST_VIDEO_INFO_WIDTH (out_info);
This has to be fixed, you are using the same width and height for all outputs. This also requires to modify the gst_tiovx_multi_scaler_init_module declaration, probably using a list of output caps instead of out_info.

2021-07-20 17:34 UTC, dchvs commented on ext/tiovx/gsttiovxmultiscaler.c
> +    multiscaler->output[i].width = (vx_int32) GST_VIDEO_INFO_WIDTH (out_info);
Thank you @jafet-chaves, I just updated my class with your SIMO GList approach to handle the output caps  :slightly_smiling_face:.

2021-07-20 17:36 UTC, dchvs commented on tests/check/gsttiovxmultiscaler.c
> +GST_START_TEST (test_init_module)
It's the unit test to the module initialization.

2021-07-20 19:15 UTC, dchvs commented on ext/tiovx/gsttiovxmultiscaler.c
> +static GstStaticPadTemplate src_template = GST_STATIC_PAD_TEMPLATE ("src",
Alright.

2021-07-20 19:52 UTC, dchvs commented on ext/tiovx/gsttiovxmultiscaler.c
> +      "tiovxmultiscaler", 0, "debug category for the tiovxmultiscaler element");
As agreed, let's keep it as TI wants it, tiovxmultiscale.

2021-07-21 17:50 UTC, jafet-chaves commented on tests/check/gsttiovxmultiscaler.c
> +  src_caps_list = g_list_alloc ();
This creates a bug, the first GList you are leaving it empty, I recommend to use g_list_alloc or g_list_append instead always to expand the list and underneath g_list_alloc is called

2021-07-21 19:34 UTC, michaelgruner requested changes

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +      g_param_spec_string ("default-target", "TIVX default target",
We want this to be a `g_param_spec_enum` not a string. Please tackle this in a new pr

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +static ScalerObj _scaler_obj;
No, we can never have this global. This will break as soon as we have two instances of the multiscaler. they will both attempt to use this global instance.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +      self->default_target = g_value_get_string (value);
for strings you always use `g_value_dup_string`. This means that you need to free the previous string.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  self->scaler_obj = &_scaler_obj;
This cannot be a global instance.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  self->num_outputs = DEFAULT_NUM_OUTPUTS;
Initialize graph

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  self->default_target = DEFAULT_PROP_TARGET;
In the `set_property` you'll need to use `g_value_dup_string` which forces you do free the last string. As such, make a copy here (using g_strdup) so that you can free it without problems there.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  multiscaler->input.bufq_depth = (vx_int32) in_pool_size;
Remove uneeded casts.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +    src_caps = g_list_next (src_caps_list)->data;
This will always return the same caps. You are not iterating. You need to do something like:
```c
GstCaps *caps = (GstCaps *)src_caps_list->data;
src_caps_list = g_list_next (src_caps_list);
```

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  }
Please confirm with @jafet-chaves if this is done in the parent class

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  self->graph = graph;
Why do we need to save this? we shouldn't

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  }
Is this order okay? we delete first and then deinit? sounds strange to me.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.c
> +  }
Also, null out everything you free.

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.h
> +#define MAX_POOL_SIZE 16
Where did this value come from?

2021-07-21 19:34 UTC, michaelgruner commented on ext/tiovx/gsttiovxmultiscaler.h
> +#define MIN_POOL_SIZE 2
Move to the source file.

2021-07-21 22:52 UTC, dchvs commented on ext/tiovx/gsttiovxmultiscaler.c
> +  self->graph = graph;
We keep it to verify the graph later on.

2021-07-21 22:56 UTC, dchvs commented on ext/tiovx/gsttiovxmultiscaler.h
> +#define MAX_POOL_SIZE 16
It corresponds to the max. `bufq_depth` the modules image object supports.

2021-07-22 21:22 UTC, michaelgruner approved these changes

2021-07-24 08:21 UTC, merged